package elements

import (
	"pw_server/utils/structEx"
)

type MonsterEssence struct {
	ID                        int     `elements:"name:id;type:int;size:4;text:未知;" gorm:"column:id;type:integer;autoIncrement:false;uniqueIndex;not null;" json:"id"`
	IdType                    int     `elements:"name:id_type;type:int;size:4;text:未知;" gorm:"column:id_type;type:integer;default:0;not null;" json:"id_type"`
	Name                      string  `elements:"name:name;type:unicode;size:64;text:未知;" gorm:"column:name;type:varchar(64);not null;" json:"name"`
	Prop                      string  `elements:"name:prop;type:unicode;size:32;text:未知;" gorm:"column:prop;type:varchar(32);not null;" json:"prop"`
	Desc                      string  `elements:"name:desc;type:unicode;size:32;text:未知;" gorm:"column:desc;type:varchar(32);not null;" json:"desc"`
	Faction                   int     `elements:"name:faction;type:int;size:4;text:未知;" gorm:"column:faction;type:integer;default:0;not null;" json:"faction"`
	MonsterFaction            int     `elements:"name:monster_faction;type:int;size:4;text:未知;" gorm:"column:monster_faction;type:integer;default:0;not null;" json:"monster_faction"`
	FileModel                 string  `elements:"name:file_model;type:gbk;size:128;text:未知;" gorm:"column:file_model;type:varchar(128);not null;" json:"file_model"`
	FileGfxShort              string  `elements:"name:file_gfx_short;type:gbk;size:128;text:未知;" gorm:"column:file_gfx_short;type:varchar(128);not null;" json:"file_gfx_short"`
	FileGfxShortHit           string  `elements:"name:file_gfx_short_hit;type:gbk;size:128;text:未知;" gorm:"column:file_gfx_short_hit;type:varchar(128);not null;" json:"file_gfx_short_hit"`
	Size                      float32 `elements:"name:size;type:float;size:4;text:未知;" gorm:"column:size;type:float;default:0;not null;" json:"size"`
	DamageDelay               float32 `elements:"name:damage_delay;type:float;size:4;text:未知;" gorm:"column:damage_delay;type:float;default:0;not null;" json:"damage_delay"`
	IdStrategy                int     `elements:"name:id_strategy;type:int;size:4;text:未知;" gorm:"column:id_strategy;type:integer;default:0;not null;" json:"id_strategy"`
	RoleInWar                 int     `elements:"name:role_in_war;type:int;size:4;text:未知;" gorm:"column:role_in_war;type:integer;default:0;not null;" json:"role_in_war"`
	Level                     int     `elements:"name:level;type:int;size:4;text:未知;" gorm:"column:level;type:integer;default:0;not null;" json:"level"`
	ShowLevel                 int     `elements:"name:show_level;type:int;size:4;text:未知;" gorm:"column:show_level;type:integer;default:0;not null;" json:"show_level"`
	IdPetEggCaptured          int     `elements:"name:id_pet_egg_captured;type:int;size:4;text:未知;" gorm:"column:id_pet_egg_captured;type:integer;default:0;not null;" json:"id_pet_egg_captured"`
	Life                      int     `elements:"name:life;type:int;size:4;text:未知;" gorm:"column:life;type:integer;default:0;not null;" json:"life"`
	Defence                   int     `elements:"name:defence;type:int;size:4;text:未知;" gorm:"column:defence;type:integer;default:0;not null;" json:"defence"`
	MagicDefences1            int     `elements:"name:magic_defences_1;type:int;size:4;text:未知;" gorm:"column:magic_defences_1;type:integer;default:0;not null;" json:"magic_defences_1"`
	MagicDefences2            int     `elements:"name:magic_defences_2;type:int;size:4;text:未知;" gorm:"column:magic_defences_2;type:integer;default:0;not null;" json:"magic_defences_2"`
	MagicDefences3            int     `elements:"name:magic_defences_3;type:int;size:4;text:未知;" gorm:"column:magic_defences_3;type:integer;default:0;not null;" json:"magic_defences_3"`
	MagicDefences4            int     `elements:"name:magic_defences_4;type:int;size:4;text:未知;" gorm:"column:magic_defences_4;type:integer;default:0;not null;" json:"magic_defences_4"`
	MagicDefences5            int     `elements:"name:magic_defences_5;type:int;size:4;text:未知;" gorm:"column:magic_defences_5;type:integer;default:0;not null;" json:"magic_defences_5"`
	ImmuneType                int     `elements:"name:immune_type;type:int;size:4;text:未知;" gorm:"column:immune_type;type:integer;default:0;not null;" json:"immune_type"`
	Exp                       int     `elements:"name:exp;type:int;size:4;text:未知;" gorm:"column:exp;type:integer;default:0;not null;" json:"exp"`
	Skillpoint                int     `elements:"name:skillpoint;type:int;size:4;text:未知;" gorm:"column:skillpoint;type:integer;default:0;not null;" json:"skillpoint"`
	MoneyAverage              int     `elements:"name:money_average;type:int;size:4;text:未知;" gorm:"column:money_average;type:integer;default:0;not null;" json:"money_average"`
	MoneyVar                  int     `elements:"name:money_var;type:int;size:4;text:未知;" gorm:"column:money_var;type:integer;default:0;not null;" json:"money_var"`
	ShortRangeMode            int     `elements:"name:short_range_mode;type:int;size:4;text:未知;" gorm:"column:short_range_mode;type:integer;default:0;not null;" json:"short_range_mode"`
	SightRange                int     `elements:"name:sight_range;type:int;size:4;text:未知;" gorm:"column:sight_range;type:integer;default:0;not null;" json:"sight_range"`
	Attack                    int     `elements:"name:attack;type:int;size:4;text:未知;" gorm:"column:attack;type:integer;default:0;not null;" json:"attack"`
	Armor                     int     `elements:"name:armor;type:int;size:4;text:未知;" gorm:"column:armor;type:integer;default:0;not null;" json:"armor"`
	DamageMin                 int     `elements:"name:damage_min;type:int;size:4;text:未知;" gorm:"column:damage_min;type:integer;default:0;not null;" json:"damage_min"`
	DamageMax                 int     `elements:"name:damage_max;type:int;size:4;text:未知;" gorm:"column:damage_max;type:integer;default:0;not null;" json:"damage_max"`
	MagicDamagesExt1DamageMin int     `elements:"name:magic_damages_ext_1_damage_min;type:int;size:4;text:未知;" gorm:"column:magic_damages_ext_1_damage_min;type:integer;default:0;not null;" json:"magic_damages_ext_1_damage_min"`
	MagicDamagesExt1DamageMax int     `elements:"name:magic_damages_ext_1_damage_max;type:int;size:4;text:未知;" gorm:"column:magic_damages_ext_1_damage_max;type:integer;default:0;not null;" json:"magic_damages_ext_1_damage_max"`
	MagicDamagesExt2DamageMin int     `elements:"name:magic_damages_ext_2_damage_min;type:int;size:4;text:未知;" gorm:"column:magic_damages_ext_2_damage_min;type:integer;default:0;not null;" json:"magic_damages_ext_2_damage_min"`
	MagicDamagesExt2DamageMax int     `elements:"name:magic_damages_ext_2_damage_max;type:int;size:4;text:未知;" gorm:"column:magic_damages_ext_2_damage_max;type:integer;default:0;not null;" json:"magic_damages_ext_2_damage_max"`
	MagicDamagesExt3DamageMin int     `elements:"name:magic_damages_ext_3_damage_min;type:int;size:4;text:未知;" gorm:"column:magic_damages_ext_3_damage_min;type:integer;default:0;not null;" json:"magic_damages_ext_3_damage_min"`
	MagicDamagesExt3DamageMax int     `elements:"name:magic_damages_ext_3_damage_max;type:int;size:4;text:未知;" gorm:"column:magic_damages_ext_3_damage_max;type:integer;default:0;not null;" json:"magic_damages_ext_3_damage_max"`
	MagicDamagesExt4DamageMin int     `elements:"name:magic_damages_ext_4_damage_min;type:int;size:4;text:未知;" gorm:"column:magic_damages_ext_4_damage_min;type:integer;default:0;not null;" json:"magic_damages_ext_4_damage_min"`
	MagicDamagesExt4DamageMax int     `elements:"name:magic_damages_ext_4_damage_max;type:int;size:4;text:未知;" gorm:"column:magic_damages_ext_4_damage_max;type:integer;default:0;not null;" json:"magic_damages_ext_4_damage_max"`
	MagicDamagesExt5DamageMin int     `elements:"name:magic_damages_ext_5_damage_min;type:int;size:4;text:未知;" gorm:"column:magic_damages_ext_5_damage_min;type:integer;default:0;not null;" json:"magic_damages_ext_5_damage_min"`
	MagicDamagesExt5DamageMax int     `elements:"name:magic_damages_ext_5_damage_max;type:int;size:4;text:未知;" gorm:"column:magic_damages_ext_5_damage_max;type:integer;default:0;not null;" json:"magic_damages_ext_5_damage_max"`
	AttackRange               float32 `elements:"name:attack_range;type:float;size:4;text:未知;" gorm:"column:attack_range;type:float;default:0;not null;" json:"attack_range"`
	AttackSpeed               float32 `elements:"name:attack_speed;type:float;size:4;text:未知;" gorm:"column:attack_speed;type:float;default:0;not null;" json:"attack_speed"`
	MagicDamageMin            int     `elements:"name:magic_damage_min;type:int;size:4;text:未知;" gorm:"column:magic_damage_min;type:integer;default:0;not null;" json:"magic_damage_min"`
	MagicDamageMax            int     `elements:"name:magic_damage_max;type:int;size:4;text:未知;" gorm:"column:magic_damage_max;type:integer;default:0;not null;" json:"magic_damage_max"`
	IdSkill                   int     `elements:"name:id_skill;type:int;size:4;text:未知;" gorm:"column:id_skill;type:integer;default:0;not null;" json:"id_skill"`
	SkillLevel                int     `elements:"name:skill_level;type:int;size:4;text:未知;" gorm:"column:skill_level;type:integer;default:0;not null;" json:"skill_level"`
	HpRegenerate              int     `elements:"name:hp_regenerate;type:int;size:4;text:未知;" gorm:"column:hp_regenerate;type:integer;default:0;not null;" json:"hp_regenerate"`
	AggressiveMode            int     `elements:"name:aggressive_mode;type:int;size:4;text:未知;" gorm:"column:aggressive_mode;type:integer;default:0;not null;" json:"aggressive_mode"`
	MonsterFactionAskHelp     int     `elements:"name:monster_faction_ask_help;type:int;size:4;text:未知;" gorm:"column:monster_faction_ask_help;type:integer;default:0;not null;" json:"monster_faction_ask_help"`
	MonsterFactionCanHelp     int     `elements:"name:monster_faction_can_help;type:int;size:4;text:未知;" gorm:"column:monster_faction_can_help;type:integer;default:0;not null;" json:"monster_faction_can_help"`
	AggroRange                float32 `elements:"name:aggro_range;type:float;size:4;text:未知;" gorm:"column:aggro_range;type:float;default:0;not null;" json:"aggro_range"`
	AggroTime                 float32 `elements:"name:aggro_time;type:float;size:4;text:未知;" gorm:"column:aggro_time;type:float;default:0;not null;" json:"aggro_time"`
	InhabitType               int     `elements:"name:inhabit_type;type:int;size:4;text:未知;" gorm:"column:inhabit_type;type:integer;default:0;not null;" json:"inhabit_type"`
	PatrollMode               int     `elements:"name:patroll_mode;type:int;size:4;text:未知;" gorm:"column:patroll_mode;type:integer;default:0;not null;" json:"patroll_mode"`
	StandMode                 int     `elements:"name:stand_mode;type:int;size:4;text:未知;" gorm:"column:stand_mode;type:integer;default:0;not null;" json:"stand_mode"`
	WalkSpeed                 float32 `elements:"name:walk_speed;type:float;size:4;text:未知;" gorm:"column:walk_speed;type:float;default:0;not null;" json:"walk_speed"`
	RunSpeed                  float32 `elements:"name:run_speed;type:float;size:4;text:未知;" gorm:"column:run_speed;type:float;default:0;not null;" json:"run_speed"`
	FlySpeed                  float32 `elements:"name:fly_speed;type:float;size:4;text:未知;" gorm:"column:fly_speed;type:float;default:0;not null;" json:"fly_speed"`
	SwimSpeed                 float32 `elements:"name:swim_speed;type:float;size:4;text:未知;" gorm:"column:swim_speed;type:float;default:0;not null;" json:"swim_speed"`
	CommonStrategy            int     `elements:"name:common_strategy;type:int;size:4;text:未知;" gorm:"column:common_strategy;type:integer;default:0;not null;" json:"common_strategy"`
	AggroStrategy1Id          int     `elements:"name:aggro_strategy_1_id;type:int;size:4;text:未知;" gorm:"column:aggro_strategy_1_id;type:integer;default:0;not null;" json:"aggro_strategy_1_id"`
	AggroStrategy1Probability float32 `elements:"name:aggro_strategy_1_probability;type:float;size:4;text:未知;" gorm:"column:aggro_strategy_1_probability;type:float;default:0;not null;" json:"aggro_strategy_1_probability"`
	AggroStrategy2Id          int     `elements:"name:aggro_strategy_2_id;type:int;size:4;text:未知;" gorm:"column:aggro_strategy_2_id;type:integer;default:0;not null;" json:"aggro_strategy_2_id"`
	AggroStrategy2Probability float32 `elements:"name:aggro_strategy_2_probability;type:float;size:4;text:未知;" gorm:"column:aggro_strategy_2_probability;type:float;default:0;not null;" json:"aggro_strategy_2_probability"`
	AggroStrategy3Id          int     `elements:"name:aggro_strategy_3_id;type:int;size:4;text:未知;" gorm:"column:aggro_strategy_3_id;type:integer;default:0;not null;" json:"aggro_strategy_3_id"`
	AggroStrategy3Probability float32 `elements:"name:aggro_strategy_3_probability;type:float;size:4;text:未知;" gorm:"column:aggro_strategy_3_probability;type:float;default:0;not null;" json:"aggro_strategy_3_probability"`
	AggroStrategy4Id          int     `elements:"name:aggro_strategy_4_id;type:int;size:4;text:未知;" gorm:"column:aggro_strategy_4_id;type:integer;default:0;not null;" json:"aggro_strategy_4_id"`
	AggroStrategy4Probability float32 `elements:"name:aggro_strategy_4_probability;type:float;size:4;text:未知;" gorm:"column:aggro_strategy_4_probability;type:float;default:0;not null;" json:"aggro_strategy_4_probability"`
	SkillHp751IdSkill         int     `elements:"name:skill_hp75_1_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp75_1_id_skill;type:integer;default:0;not null;" json:"skill_hp75_1_id_skill"`
	SkillHp751Level           int     `elements:"name:skill_hp75_1_level;type:int;size:4;text:未知;" gorm:"column:skill_hp75_1_level;type:integer;default:0;not null;" json:"skill_hp75_1_level"`
	SkillHp751Probability     float32 `elements:"name:skill_hp75_1_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp75_1_probability;type:float;default:0;not null;" json:"skill_hp75_1_probability"`
	SkillHp752IdSkill         int     `elements:"name:skill_hp75_2_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp75_2_id_skill;type:integer;default:0;not null;" json:"skill_hp75_2_id_skill"`
	SkillHp752Level           int     `elements:"name:skill_hp75_2_level;type:int;size:4;text:未知;" gorm:"column:skill_hp75_2_level;type:integer;default:0;not null;" json:"skill_hp75_2_level"`
	SkillHp752Probability     float32 `elements:"name:skill_hp75_2_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp75_2_probability;type:float;default:0;not null;" json:"skill_hp75_2_probability"`
	SkillHp753IdSkill         int     `elements:"name:skill_hp75_3_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp75_3_id_skill;type:integer;default:0;not null;" json:"skill_hp75_3_id_skill"`
	SkillHp753Level           int     `elements:"name:skill_hp75_3_level;type:int;size:4;text:未知;" gorm:"column:skill_hp75_3_level;type:integer;default:0;not null;" json:"skill_hp75_3_level"`
	SkillHp753Probability     float32 `elements:"name:skill_hp75_3_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp75_3_probability;type:float;default:0;not null;" json:"skill_hp75_3_probability"`
	SkillHp754IdSkill         int     `elements:"name:skill_hp75_4_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp75_4_id_skill;type:integer;default:0;not null;" json:"skill_hp75_4_id_skill"`
	SkillHp754Level           int     `elements:"name:skill_hp75_4_level;type:int;size:4;text:未知;" gorm:"column:skill_hp75_4_level;type:integer;default:0;not null;" json:"skill_hp75_4_level"`
	SkillHp754Probability     float32 `elements:"name:skill_hp75_4_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp75_4_probability;type:float;default:0;not null;" json:"skill_hp75_4_probability"`
	SkillHp755IdSkill         int     `elements:"name:skill_hp75_5_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp75_5_id_skill;type:integer;default:0;not null;" json:"skill_hp75_5_id_skill"`
	SkillHp755Level           int     `elements:"name:skill_hp75_5_level;type:int;size:4;text:未知;" gorm:"column:skill_hp75_5_level;type:integer;default:0;not null;" json:"skill_hp75_5_level"`
	SkillHp755Probability     float32 `elements:"name:skill_hp75_5_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp75_5_probability;type:float;default:0;not null;" json:"skill_hp75_5_probability"`
	SkillHp501IdSkill         int     `elements:"name:skill_hp50_1_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp50_1_id_skill;type:integer;default:0;not null;" json:"skill_hp50_1_id_skill"`
	SkillHp501Level           int     `elements:"name:skill_hp50_1_level;type:int;size:4;text:未知;" gorm:"column:skill_hp50_1_level;type:integer;default:0;not null;" json:"skill_hp50_1_level"`
	SkillHp501Probability     float32 `elements:"name:skill_hp50_1_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp50_1_probability;type:float;default:0;not null;" json:"skill_hp50_1_probability"`
	SkillHp502IdSkill         int     `elements:"name:skill_hp50_2_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp50_2_id_skill;type:integer;default:0;not null;" json:"skill_hp50_2_id_skill"`
	SkillHp502Level           int     `elements:"name:skill_hp50_2_level;type:int;size:4;text:未知;" gorm:"column:skill_hp50_2_level;type:integer;default:0;not null;" json:"skill_hp50_2_level"`
	SkillHp502Probability     float32 `elements:"name:skill_hp50_2_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp50_2_probability;type:float;default:0;not null;" json:"skill_hp50_2_probability"`
	SkillHp503IdSkill         int     `elements:"name:skill_hp50_3_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp50_3_id_skill;type:integer;default:0;not null;" json:"skill_hp50_3_id_skill"`
	SkillHp503Level           int     `elements:"name:skill_hp50_3_level;type:int;size:4;text:未知;" gorm:"column:skill_hp50_3_level;type:integer;default:0;not null;" json:"skill_hp50_3_level"`
	SkillHp503Probability     float32 `elements:"name:skill_hp50_3_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp50_3_probability;type:float;default:0;not null;" json:"skill_hp50_3_probability"`
	SkillHp504IdSkill         int     `elements:"name:skill_hp50_4_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp50_4_id_skill;type:integer;default:0;not null;" json:"skill_hp50_4_id_skill"`
	SkillHp504Level           int     `elements:"name:skill_hp50_4_level;type:int;size:4;text:未知;" gorm:"column:skill_hp50_4_level;type:integer;default:0;not null;" json:"skill_hp50_4_level"`
	SkillHp504Probability     float32 `elements:"name:skill_hp50_4_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp50_4_probability;type:float;default:0;not null;" json:"skill_hp50_4_probability"`
	SkillHp505IdSkill         int     `elements:"name:skill_hp50_5_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp50_5_id_skill;type:integer;default:0;not null;" json:"skill_hp50_5_id_skill"`
	SkillHp505Level           int     `elements:"name:skill_hp50_5_level;type:int;size:4;text:未知;" gorm:"column:skill_hp50_5_level;type:integer;default:0;not null;" json:"skill_hp50_5_level"`
	SkillHp505Probability     float32 `elements:"name:skill_hp50_5_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp50_5_probability;type:float;default:0;not null;" json:"skill_hp50_5_probability"`
	SkillHp251IdSkill         int     `elements:"name:skill_hp25_1_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp25_1_id_skill;type:integer;default:0;not null;" json:"skill_hp25_1_id_skill"`
	SkillHp251Level           int     `elements:"name:skill_hp25_1_level;type:int;size:4;text:未知;" gorm:"column:skill_hp25_1_level;type:integer;default:0;not null;" json:"skill_hp25_1_level"`
	SkillHp251Probability     float32 `elements:"name:skill_hp25_1_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp25_1_probability;type:float;default:0;not null;" json:"skill_hp25_1_probability"`
	SkillHp252IdSkill         int     `elements:"name:skill_hp25_2_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp25_2_id_skill;type:integer;default:0;not null;" json:"skill_hp25_2_id_skill"`
	SkillHp252Level           int     `elements:"name:skill_hp25_2_level;type:int;size:4;text:未知;" gorm:"column:skill_hp25_2_level;type:integer;default:0;not null;" json:"skill_hp25_2_level"`
	SkillHp252Probability     float32 `elements:"name:skill_hp25_2_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp25_2_probability;type:float;default:0;not null;" json:"skill_hp25_2_probability"`
	SkillHp253IdSkill         int     `elements:"name:skill_hp25_3_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp25_3_id_skill;type:integer;default:0;not null;" json:"skill_hp25_3_id_skill"`
	SkillHp253Level           int     `elements:"name:skill_hp25_3_level;type:int;size:4;text:未知;" gorm:"column:skill_hp25_3_level;type:integer;default:0;not null;" json:"skill_hp25_3_level"`
	SkillHp253Probability     float32 `elements:"name:skill_hp25_3_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp25_3_probability;type:float;default:0;not null;" json:"skill_hp25_3_probability"`
	SkillHp254IdSkill         int     `elements:"name:skill_hp25_4_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp25_4_id_skill;type:integer;default:0;not null;" json:"skill_hp25_4_id_skill"`
	SkillHp254Level           int     `elements:"name:skill_hp25_4_level;type:int;size:4;text:未知;" gorm:"column:skill_hp25_4_level;type:integer;default:0;not null;" json:"skill_hp25_4_level"`
	SkillHp254Probability     float32 `elements:"name:skill_hp25_4_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp25_4_probability;type:float;default:0;not null;" json:"skill_hp25_4_probability"`
	SkillHp255IdSkill         int     `elements:"name:skill_hp25_5_id_skill;type:int;size:4;text:未知;" gorm:"column:skill_hp25_5_id_skill;type:integer;default:0;not null;" json:"skill_hp25_5_id_skill"`
	SkillHp255Level           int     `elements:"name:skill_hp25_5_level;type:int;size:4;text:未知;" gorm:"column:skill_hp25_5_level;type:integer;default:0;not null;" json:"skill_hp25_5_level"`
	SkillHp255Probability     float32 `elements:"name:skill_hp25_5_probability;type:float;size:4;text:未知;" gorm:"column:skill_hp25_5_probability;type:float;default:0;not null;" json:"skill_hp25_5_probability"`
	AfterDeath                int     `elements:"name:after_death;type:int;size:4;text:未知;" gorm:"column:after_death;type:integer;default:0;not null;" json:"after_death"`
	Skills1IdSkill            int     `elements:"name:skills_1_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_1_id_skill;type:integer;default:0;not null;" json:"skills_1_id_skill"`
	Skills1Level              int     `elements:"name:skills_1_level;type:int;size:4;text:未知;" gorm:"column:skills_1_level;type:integer;default:0;not null;" json:"skills_1_level"`
	Skills2IdSkill            int     `elements:"name:skills_2_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_2_id_skill;type:integer;default:0;not null;" json:"skills_2_id_skill"`
	Skills2Level              int     `elements:"name:skills_2_level;type:int;size:4;text:未知;" gorm:"column:skills_2_level;type:integer;default:0;not null;" json:"skills_2_level"`
	Skills3IdSkill            int     `elements:"name:skills_3_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_3_id_skill;type:integer;default:0;not null;" json:"skills_3_id_skill"`
	Skills3Level              int     `elements:"name:skills_3_level;type:int;size:4;text:未知;" gorm:"column:skills_3_level;type:integer;default:0;not null;" json:"skills_3_level"`
	Skills4IdSkill            int     `elements:"name:skills_4_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_4_id_skill;type:integer;default:0;not null;" json:"skills_4_id_skill"`
	Skills4Level              int     `elements:"name:skills_4_level;type:int;size:4;text:未知;" gorm:"column:skills_4_level;type:integer;default:0;not null;" json:"skills_4_level"`
	Skills5IdSkill            int     `elements:"name:skills_5_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_5_id_skill;type:integer;default:0;not null;" json:"skills_5_id_skill"`
	Skills5Level              int     `elements:"name:skills_5_level;type:int;size:4;text:未知;" gorm:"column:skills_5_level;type:integer;default:0;not null;" json:"skills_5_level"`
	Skills6IdSkill            int     `elements:"name:skills_6_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_6_id_skill;type:integer;default:0;not null;" json:"skills_6_id_skill"`
	Skills6Level              int     `elements:"name:skills_6_level;type:int;size:4;text:未知;" gorm:"column:skills_6_level;type:integer;default:0;not null;" json:"skills_6_level"`
	Skills7IdSkill            int     `elements:"name:skills_7_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_7_id_skill;type:integer;default:0;not null;" json:"skills_7_id_skill"`
	Skills7Level              int     `elements:"name:skills_7_level;type:int;size:4;text:未知;" gorm:"column:skills_7_level;type:integer;default:0;not null;" json:"skills_7_level"`
	Skills8IdSkill            int     `elements:"name:skills_8_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_8_id_skill;type:integer;default:0;not null;" json:"skills_8_id_skill"`
	Skills8Level              int     `elements:"name:skills_8_level;type:int;size:4;text:未知;" gorm:"column:skills_8_level;type:integer;default:0;not null;" json:"skills_8_level"`
	Skills9IdSkill            int     `elements:"name:skills_9_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_9_id_skill;type:integer;default:0;not null;" json:"skills_9_id_skill"`
	Skills9Level              int     `elements:"name:skills_9_level;type:int;size:4;text:未知;" gorm:"column:skills_9_level;type:integer;default:0;not null;" json:"skills_9_level"`
	Skills10IdSkill           int     `elements:"name:skills_10_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_10_id_skill;type:integer;default:0;not null;" json:"skills_10_id_skill"`
	Skills10Level             int     `elements:"name:skills_10_level;type:int;size:4;text:未知;" gorm:"column:skills_10_level;type:integer;default:0;not null;" json:"skills_10_level"`
	Skills11IdSkill           int     `elements:"name:skills_11_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_11_id_skill;type:integer;default:0;not null;" json:"skills_11_id_skill"`
	Skills11Level             int     `elements:"name:skills_11_level;type:int;size:4;text:未知;" gorm:"column:skills_11_level;type:integer;default:0;not null;" json:"skills_11_level"`
	Skills12IdSkill           int     `elements:"name:skills_12_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_12_id_skill;type:integer;default:0;not null;" json:"skills_12_id_skill"`
	Skills12Level             int     `elements:"name:skills_12_level;type:int;size:4;text:未知;" gorm:"column:skills_12_level;type:integer;default:0;not null;" json:"skills_12_level"`
	Skills13IdSkill           int     `elements:"name:skills_13_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_13_id_skill;type:integer;default:0;not null;" json:"skills_13_id_skill"`
	Skills13Level             int     `elements:"name:skills_13_level;type:int;size:4;text:未知;" gorm:"column:skills_13_level;type:integer;default:0;not null;" json:"skills_13_level"`
	Skills14IdSkill           int     `elements:"name:skills_14_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_14_id_skill;type:integer;default:0;not null;" json:"skills_14_id_skill"`
	Skills14Level             int     `elements:"name:skills_14_level;type:int;size:4;text:未知;" gorm:"column:skills_14_level;type:integer;default:0;not null;" json:"skills_14_level"`
	Skills15IdSkill           int     `elements:"name:skills_15_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_15_id_skill;type:integer;default:0;not null;" json:"skills_15_id_skill"`
	Skills15Level             int     `elements:"name:skills_15_level;type:int;size:4;text:未知;" gorm:"column:skills_15_level;type:integer;default:0;not null;" json:"skills_15_level"`
	Skills16IdSkill           int     `elements:"name:skills_16_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_16_id_skill;type:integer;default:0;not null;" json:"skills_16_id_skill"`
	Skills16Level             int     `elements:"name:skills_16_level;type:int;size:4;text:未知;" gorm:"column:skills_16_level;type:integer;default:0;not null;" json:"skills_16_level"`
	Skills17IdSkill           int     `elements:"name:skills_17_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_17_id_skill;type:integer;default:0;not null;" json:"skills_17_id_skill"`
	Skills17Level             int     `elements:"name:skills_17_level;type:int;size:4;text:未知;" gorm:"column:skills_17_level;type:integer;default:0;not null;" json:"skills_17_level"`
	Skills18IdSkill           int     `elements:"name:skills_18_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_18_id_skill;type:integer;default:0;not null;" json:"skills_18_id_skill"`
	Skills18Level             int     `elements:"name:skills_18_level;type:int;size:4;text:未知;" gorm:"column:skills_18_level;type:integer;default:0;not null;" json:"skills_18_level"`
	Skills19IdSkill           int     `elements:"name:skills_19_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_19_id_skill;type:integer;default:0;not null;" json:"skills_19_id_skill"`
	Skills19Level             int     `elements:"name:skills_19_level;type:int;size:4;text:未知;" gorm:"column:skills_19_level;type:integer;default:0;not null;" json:"skills_19_level"`
	Skills20IdSkill           int     `elements:"name:skills_20_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_20_id_skill;type:integer;default:0;not null;" json:"skills_20_id_skill"`
	Skills20Level             int     `elements:"name:skills_20_level;type:int;size:4;text:未知;" gorm:"column:skills_20_level;type:integer;default:0;not null;" json:"skills_20_level"`
	Skills21IdSkill           int     `elements:"name:skills_21_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_21_id_skill;type:integer;default:0;not null;" json:"skills_21_id_skill"`
	Skills21Level             int     `elements:"name:skills_21_level;type:int;size:4;text:未知;" gorm:"column:skills_21_level;type:integer;default:0;not null;" json:"skills_21_level"`
	Skills22IdSkill           int     `elements:"name:skills_22_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_22_id_skill;type:integer;default:0;not null;" json:"skills_22_id_skill"`
	Skills22Level             int     `elements:"name:skills_22_level;type:int;size:4;text:未知;" gorm:"column:skills_22_level;type:integer;default:0;not null;" json:"skills_22_level"`
	Skills23IdSkill           int     `elements:"name:skills_23_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_23_id_skill;type:integer;default:0;not null;" json:"skills_23_id_skill"`
	Skills23Level             int     `elements:"name:skills_23_level;type:int;size:4;text:未知;" gorm:"column:skills_23_level;type:integer;default:0;not null;" json:"skills_23_level"`
	Skills24IdSkill           int     `elements:"name:skills_24_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_24_id_skill;type:integer;default:0;not null;" json:"skills_24_id_skill"`
	Skills24Level             int     `elements:"name:skills_24_level;type:int;size:4;text:未知;" gorm:"column:skills_24_level;type:integer;default:0;not null;" json:"skills_24_level"`
	Skills25IdSkill           int     `elements:"name:skills_25_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_25_id_skill;type:integer;default:0;not null;" json:"skills_25_id_skill"`
	Skills25Level             int     `elements:"name:skills_25_level;type:int;size:4;text:未知;" gorm:"column:skills_25_level;type:integer;default:0;not null;" json:"skills_25_level"`
	Skills26IdSkill           int     `elements:"name:skills_26_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_26_id_skill;type:integer;default:0;not null;" json:"skills_26_id_skill"`
	Skills26Level             int     `elements:"name:skills_26_level;type:int;size:4;text:未知;" gorm:"column:skills_26_level;type:integer;default:0;not null;" json:"skills_26_level"`
	Skills27IdSkill           int     `elements:"name:skills_27_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_27_id_skill;type:integer;default:0;not null;" json:"skills_27_id_skill"`
	Skills27Level             int     `elements:"name:skills_27_level;type:int;size:4;text:未知;" gorm:"column:skills_27_level;type:integer;default:0;not null;" json:"skills_27_level"`
	Skills28IdSkill           int     `elements:"name:skills_28_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_28_id_skill;type:integer;default:0;not null;" json:"skills_28_id_skill"`
	Skills28Level             int     `elements:"name:skills_28_level;type:int;size:4;text:未知;" gorm:"column:skills_28_level;type:integer;default:0;not null;" json:"skills_28_level"`
	Skills29IdSkill           int     `elements:"name:skills_29_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_29_id_skill;type:integer;default:0;not null;" json:"skills_29_id_skill"`
	Skills29Level             int     `elements:"name:skills_29_level;type:int;size:4;text:未知;" gorm:"column:skills_29_level;type:integer;default:0;not null;" json:"skills_29_level"`
	Skills30IdSkill           int     `elements:"name:skills_30_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_30_id_skill;type:integer;default:0;not null;" json:"skills_30_id_skill"`
	Skills30Level             int     `elements:"name:skills_30_level;type:int;size:4;text:未知;" gorm:"column:skills_30_level;type:integer;default:0;not null;" json:"skills_30_level"`
	Skills31IdSkill           int     `elements:"name:skills_31_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_31_id_skill;type:integer;default:0;not null;" json:"skills_31_id_skill"`
	Skills31Level             int     `elements:"name:skills_31_level;type:int;size:4;text:未知;" gorm:"column:skills_31_level;type:integer;default:0;not null;" json:"skills_31_level"`
	Skills32IdSkill           int     `elements:"name:skills_32_id_skill;type:int;size:4;text:未知;" gorm:"column:skills_32_id_skill;type:integer;default:0;not null;" json:"skills_32_id_skill"`
	Skills32Level             int     `elements:"name:skills_32_level;type:int;size:4;text:未知;" gorm:"column:skills_32_level;type:integer;default:0;not null;" json:"skills_32_level"`
	ProbabilityDropNum0       float32 `elements:"name:probability_drop_num0;type:float;size:4;text:未知;" gorm:"column:probability_drop_num0;type:float;default:0;not null;" json:"probability_drop_num0"`
	ProbabilityDropNum1       float32 `elements:"name:probability_drop_num1;type:float;size:4;text:未知;" gorm:"column:probability_drop_num1;type:float;default:0;not null;" json:"probability_drop_num1"`
	ProbabilityDropNum2       float32 `elements:"name:probability_drop_num2;type:float;size:4;text:未知;" gorm:"column:probability_drop_num2;type:float;default:0;not null;" json:"probability_drop_num2"`
	ProbabilityDropNum3       float32 `elements:"name:probability_drop_num3;type:float;size:4;text:未知;" gorm:"column:probability_drop_num3;type:float;default:0;not null;" json:"probability_drop_num3"`
	DropTimes                 int     `elements:"name:drop_times;type:int;size:4;text:未知;" gorm:"column:drop_times;type:integer;default:0;not null;" json:"drop_times"`
	DropProtected             int     `elements:"name:drop_protected;type:int;size:4;text:未知;" gorm:"column:drop_protected;type:integer;default:0;not null;" json:"drop_protected"`
	DropMatters1Id            int     `elements:"name:drop_matters_1_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_1_id;type:integer;default:0;not null;" json:"drop_matters_1_id"`
	DropMatters1Probability   float32 `elements:"name:drop_matters_1_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_1_probability;type:float;default:0;not null;" json:"drop_matters_1_probability"`
	DropMatters2Id            int     `elements:"name:drop_matters_2_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_2_id;type:integer;default:0;not null;" json:"drop_matters_2_id"`
	DropMatters2Probability   float32 `elements:"name:drop_matters_2_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_2_probability;type:float;default:0;not null;" json:"drop_matters_2_probability"`
	DropMatters3Id            int     `elements:"name:drop_matters_3_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_3_id;type:integer;default:0;not null;" json:"drop_matters_3_id"`
	DropMatters3Probability   float32 `elements:"name:drop_matters_3_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_3_probability;type:float;default:0;not null;" json:"drop_matters_3_probability"`
	DropMatters4Id            int     `elements:"name:drop_matters_4_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_4_id;type:integer;default:0;not null;" json:"drop_matters_4_id"`
	DropMatters4Probability   float32 `elements:"name:drop_matters_4_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_4_probability;type:float;default:0;not null;" json:"drop_matters_4_probability"`
	DropMatters5Id            int     `elements:"name:drop_matters_5_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_5_id;type:integer;default:0;not null;" json:"drop_matters_5_id"`
	DropMatters5Probability   float32 `elements:"name:drop_matters_5_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_5_probability;type:float;default:0;not null;" json:"drop_matters_5_probability"`
	DropMatters6Id            int     `elements:"name:drop_matters_6_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_6_id;type:integer;default:0;not null;" json:"drop_matters_6_id"`
	DropMatters6Probability   float32 `elements:"name:drop_matters_6_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_6_probability;type:float;default:0;not null;" json:"drop_matters_6_probability"`
	DropMatters7Id            int     `elements:"name:drop_matters_7_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_7_id;type:integer;default:0;not null;" json:"drop_matters_7_id"`
	DropMatters7Probability   float32 `elements:"name:drop_matters_7_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_7_probability;type:float;default:0;not null;" json:"drop_matters_7_probability"`
	DropMatters8Id            int     `elements:"name:drop_matters_8_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_8_id;type:integer;default:0;not null;" json:"drop_matters_8_id"`
	DropMatters8Probability   float32 `elements:"name:drop_matters_8_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_8_probability;type:float;default:0;not null;" json:"drop_matters_8_probability"`
	DropMatters9Id            int     `elements:"name:drop_matters_9_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_9_id;type:integer;default:0;not null;" json:"drop_matters_9_id"`
	DropMatters9Probability   float32 `elements:"name:drop_matters_9_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_9_probability;type:float;default:0;not null;" json:"drop_matters_9_probability"`
	DropMatters10Id           int     `elements:"name:drop_matters_10_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_10_id;type:integer;default:0;not null;" json:"drop_matters_10_id"`
	DropMatters10Probability  float32 `elements:"name:drop_matters_10_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_10_probability;type:float;default:0;not null;" json:"drop_matters_10_probability"`
	DropMatters11Id           int     `elements:"name:drop_matters_11_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_11_id;type:integer;default:0;not null;" json:"drop_matters_11_id"`
	DropMatters11Probability  float32 `elements:"name:drop_matters_11_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_11_probability;type:float;default:0;not null;" json:"drop_matters_11_probability"`
	DropMatters12Id           int     `elements:"name:drop_matters_12_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_12_id;type:integer;default:0;not null;" json:"drop_matters_12_id"`
	DropMatters12Probability  float32 `elements:"name:drop_matters_12_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_12_probability;type:float;default:0;not null;" json:"drop_matters_12_probability"`
	DropMatters13Id           int     `elements:"name:drop_matters_13_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_13_id;type:integer;default:0;not null;" json:"drop_matters_13_id"`
	DropMatters13Probability  float32 `elements:"name:drop_matters_13_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_13_probability;type:float;default:0;not null;" json:"drop_matters_13_probability"`
	DropMatters14Id           int     `elements:"name:drop_matters_14_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_14_id;type:integer;default:0;not null;" json:"drop_matters_14_id"`
	DropMatters14Probability  float32 `elements:"name:drop_matters_14_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_14_probability;type:float;default:0;not null;" json:"drop_matters_14_probability"`
	DropMatters15Id           int     `elements:"name:drop_matters_15_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_15_id;type:integer;default:0;not null;" json:"drop_matters_15_id"`
	DropMatters15Probability  float32 `elements:"name:drop_matters_15_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_15_probability;type:float;default:0;not null;" json:"drop_matters_15_probability"`
	DropMatters16Id           int     `elements:"name:drop_matters_16_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_16_id;type:integer;default:0;not null;" json:"drop_matters_16_id"`
	DropMatters16Probability  float32 `elements:"name:drop_matters_16_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_16_probability;type:float;default:0;not null;" json:"drop_matters_16_probability"`
	DropMatters17Id           int     `elements:"name:drop_matters_17_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_17_id;type:integer;default:0;not null;" json:"drop_matters_17_id"`
	DropMatters17Probability  float32 `elements:"name:drop_matters_17_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_17_probability;type:float;default:0;not null;" json:"drop_matters_17_probability"`
	DropMatters18Id           int     `elements:"name:drop_matters_18_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_18_id;type:integer;default:0;not null;" json:"drop_matters_18_id"`
	DropMatters18Probability  float32 `elements:"name:drop_matters_18_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_18_probability;type:float;default:0;not null;" json:"drop_matters_18_probability"`
	DropMatters19Id           int     `elements:"name:drop_matters_19_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_19_id;type:integer;default:0;not null;" json:"drop_matters_19_id"`
	DropMatters19Probability  float32 `elements:"name:drop_matters_19_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_19_probability;type:float;default:0;not null;" json:"drop_matters_19_probability"`
	DropMatters20Id           int     `elements:"name:drop_matters_20_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_20_id;type:integer;default:0;not null;" json:"drop_matters_20_id"`
	DropMatters20Probability  float32 `elements:"name:drop_matters_20_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_20_probability;type:float;default:0;not null;" json:"drop_matters_20_probability"`
	DropMatters21Id           int     `elements:"name:drop_matters_21_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_21_id;type:integer;default:0;not null;" json:"drop_matters_21_id"`
	DropMatters21Probability  float32 `elements:"name:drop_matters_21_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_21_probability;type:float;default:0;not null;" json:"drop_matters_21_probability"`
	DropMatters22Id           int     `elements:"name:drop_matters_22_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_22_id;type:integer;default:0;not null;" json:"drop_matters_22_id"`
	DropMatters22Probability  float32 `elements:"name:drop_matters_22_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_22_probability;type:float;default:0;not null;" json:"drop_matters_22_probability"`
	DropMatters23Id           int     `elements:"name:drop_matters_23_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_23_id;type:integer;default:0;not null;" json:"drop_matters_23_id"`
	DropMatters23Probability  float32 `elements:"name:drop_matters_23_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_23_probability;type:float;default:0;not null;" json:"drop_matters_23_probability"`
	DropMatters24Id           int     `elements:"name:drop_matters_24_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_24_id;type:integer;default:0;not null;" json:"drop_matters_24_id"`
	DropMatters24Probability  float32 `elements:"name:drop_matters_24_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_24_probability;type:float;default:0;not null;" json:"drop_matters_24_probability"`
	DropMatters25Id           int     `elements:"name:drop_matters_25_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_25_id;type:integer;default:0;not null;" json:"drop_matters_25_id"`
	DropMatters25Probability  float32 `elements:"name:drop_matters_25_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_25_probability;type:float;default:0;not null;" json:"drop_matters_25_probability"`
	DropMatters26Id           int     `elements:"name:drop_matters_26_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_26_id;type:integer;default:0;not null;" json:"drop_matters_26_id"`
	DropMatters26Probability  float32 `elements:"name:drop_matters_26_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_26_probability;type:float;default:0;not null;" json:"drop_matters_26_probability"`
	DropMatters27Id           int     `elements:"name:drop_matters_27_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_27_id;type:integer;default:0;not null;" json:"drop_matters_27_id"`
	DropMatters27Probability  float32 `elements:"name:drop_matters_27_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_27_probability;type:float;default:0;not null;" json:"drop_matters_27_probability"`
	DropMatters28Id           int     `elements:"name:drop_matters_28_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_28_id;type:integer;default:0;not null;" json:"drop_matters_28_id"`
	DropMatters28Probability  float32 `elements:"name:drop_matters_28_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_28_probability;type:float;default:0;not null;" json:"drop_matters_28_probability"`
	DropMatters29Id           int     `elements:"name:drop_matters_29_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_29_id;type:integer;default:0;not null;" json:"drop_matters_29_id"`
	DropMatters29Probability  float32 `elements:"name:drop_matters_29_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_29_probability;type:float;default:0;not null;" json:"drop_matters_29_probability"`
	DropMatters30Id           int     `elements:"name:drop_matters_30_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_30_id;type:integer;default:0;not null;" json:"drop_matters_30_id"`
	DropMatters30Probability  float32 `elements:"name:drop_matters_30_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_30_probability;type:float;default:0;not null;" json:"drop_matters_30_probability"`
	DropMatters31Id           int     `elements:"name:drop_matters_31_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_31_id;type:integer;default:0;not null;" json:"drop_matters_31_id"`
	DropMatters31Probability  float32 `elements:"name:drop_matters_31_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_31_probability;type:float;default:0;not null;" json:"drop_matters_31_probability"`
	DropMatters32Id           int     `elements:"name:drop_matters_32_id;type:int;size:4;text:未知;" gorm:"column:drop_matters_32_id;type:integer;default:0;not null;" json:"drop_matters_32_id"`
	DropMatters32Probability  float32 `elements:"name:drop_matters_32_probability;type:float;size:4;text:未知;" gorm:"column:drop_matters_32_probability;type:float;default:0;not null;" json:"drop_matters_32_probability"`
}

func (MonsterEssence) TableName() string {
	return "el_monsteressence"
}

func (e *MonsterEssence) GetSize() (size int, err error) {
	return structEx.GetSize(e)
}

func (e *MonsterEssence) SetData(data []byte) (err error) {
	return structEx.SetData(e, data)
}
