package elements

import (
	"pw_server/utils/structEx"
)

type NpcMakeService struct {
	ID              int    `elements:"name:id;type:int;size:4;text:未知;" gorm:"column:id;type:integer;autoIncrement:false;uniqueIndex;not null;" json:"id"`
	Name            string `elements:"name:name;type:unicode;size:64;text:未知;" gorm:"column:name;type:varchar(64);not null;" json:"name"`
	IdMakeSkill     int    `elements:"name:id_make_skill;type:int;size:4;text:未知;" gorm:"column:id_make_skill;type:integer;default:0;not null;" json:"id_make_skill"`
	Pages1PageTitle string `elements:"name:pages_1_page_title;type:unicode;size:16;text:未知;" gorm:"column:pages_1_page_title;type:varchar(16);not null;" json:"pages_1_page_title"`
	Pages1IdGoods1  int    `elements:"name:pages_1_id_goods_1;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_1;type:integer;default:0;not null;" json:"pages_1_id_goods_1"`
	Pages1IdGoods2  int    `elements:"name:pages_1_id_goods_2;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_2;type:integer;default:0;not null;" json:"pages_1_id_goods_2"`
	Pages1IdGoods3  int    `elements:"name:pages_1_id_goods_3;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_3;type:integer;default:0;not null;" json:"pages_1_id_goods_3"`
	Pages1IdGoods4  int    `elements:"name:pages_1_id_goods_4;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_4;type:integer;default:0;not null;" json:"pages_1_id_goods_4"`
	Pages1IdGoods5  int    `elements:"name:pages_1_id_goods_5;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_5;type:integer;default:0;not null;" json:"pages_1_id_goods_5"`
	Pages1IdGoods6  int    `elements:"name:pages_1_id_goods_6;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_6;type:integer;default:0;not null;" json:"pages_1_id_goods_6"`
	Pages1IdGoods7  int    `elements:"name:pages_1_id_goods_7;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_7;type:integer;default:0;not null;" json:"pages_1_id_goods_7"`
	Pages1IdGoods8  int    `elements:"name:pages_1_id_goods_8;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_8;type:integer;default:0;not null;" json:"pages_1_id_goods_8"`
	Pages1IdGoods9  int    `elements:"name:pages_1_id_goods_9;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_9;type:integer;default:0;not null;" json:"pages_1_id_goods_9"`
	Pages1IdGoods10 int    `elements:"name:pages_1_id_goods_10;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_10;type:integer;default:0;not null;" json:"pages_1_id_goods_10"`
	Pages1IdGoods11 int    `elements:"name:pages_1_id_goods_11;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_11;type:integer;default:0;not null;" json:"pages_1_id_goods_11"`
	Pages1IdGoods12 int    `elements:"name:pages_1_id_goods_12;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_12;type:integer;default:0;not null;" json:"pages_1_id_goods_12"`
	Pages1IdGoods13 int    `elements:"name:pages_1_id_goods_13;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_13;type:integer;default:0;not null;" json:"pages_1_id_goods_13"`
	Pages1IdGoods14 int    `elements:"name:pages_1_id_goods_14;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_14;type:integer;default:0;not null;" json:"pages_1_id_goods_14"`
	Pages1IdGoods15 int    `elements:"name:pages_1_id_goods_15;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_15;type:integer;default:0;not null;" json:"pages_1_id_goods_15"`
	Pages1IdGoods16 int    `elements:"name:pages_1_id_goods_16;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_16;type:integer;default:0;not null;" json:"pages_1_id_goods_16"`
	Pages1IdGoods17 int    `elements:"name:pages_1_id_goods_17;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_17;type:integer;default:0;not null;" json:"pages_1_id_goods_17"`
	Pages1IdGoods18 int    `elements:"name:pages_1_id_goods_18;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_18;type:integer;default:0;not null;" json:"pages_1_id_goods_18"`
	Pages1IdGoods19 int    `elements:"name:pages_1_id_goods_19;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_19;type:integer;default:0;not null;" json:"pages_1_id_goods_19"`
	Pages1IdGoods20 int    `elements:"name:pages_1_id_goods_20;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_20;type:integer;default:0;not null;" json:"pages_1_id_goods_20"`
	Pages1IdGoods21 int    `elements:"name:pages_1_id_goods_21;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_21;type:integer;default:0;not null;" json:"pages_1_id_goods_21"`
	Pages1IdGoods22 int    `elements:"name:pages_1_id_goods_22;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_22;type:integer;default:0;not null;" json:"pages_1_id_goods_22"`
	Pages1IdGoods23 int    `elements:"name:pages_1_id_goods_23;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_23;type:integer;default:0;not null;" json:"pages_1_id_goods_23"`
	Pages1IdGoods24 int    `elements:"name:pages_1_id_goods_24;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_24;type:integer;default:0;not null;" json:"pages_1_id_goods_24"`
	Pages1IdGoods25 int    `elements:"name:pages_1_id_goods_25;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_25;type:integer;default:0;not null;" json:"pages_1_id_goods_25"`
	Pages1IdGoods26 int    `elements:"name:pages_1_id_goods_26;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_26;type:integer;default:0;not null;" json:"pages_1_id_goods_26"`
	Pages1IdGoods27 int    `elements:"name:pages_1_id_goods_27;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_27;type:integer;default:0;not null;" json:"pages_1_id_goods_27"`
	Pages1IdGoods28 int    `elements:"name:pages_1_id_goods_28;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_28;type:integer;default:0;not null;" json:"pages_1_id_goods_28"`
	Pages1IdGoods29 int    `elements:"name:pages_1_id_goods_29;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_29;type:integer;default:0;not null;" json:"pages_1_id_goods_29"`
	Pages1IdGoods30 int    `elements:"name:pages_1_id_goods_30;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_30;type:integer;default:0;not null;" json:"pages_1_id_goods_30"`
	Pages1IdGoods31 int    `elements:"name:pages_1_id_goods_31;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_31;type:integer;default:0;not null;" json:"pages_1_id_goods_31"`
	Pages1IdGoods32 int    `elements:"name:pages_1_id_goods_32;type:int;size:4;text:未知;" gorm:"column:pages_1_id_goods_32;type:integer;default:0;not null;" json:"pages_1_id_goods_32"`
	Pages2PageTitle string `elements:"name:pages_2_page_title;type:unicode;size:16;text:未知;" gorm:"column:pages_2_page_title;type:varchar(16);not null;" json:"pages_2_page_title"`
	Pages2IdGoods1  int    `elements:"name:pages_2_id_goods_1;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_1;type:integer;default:0;not null;" json:"pages_2_id_goods_1"`
	Pages2IdGoods2  int    `elements:"name:pages_2_id_goods_2;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_2;type:integer;default:0;not null;" json:"pages_2_id_goods_2"`
	Pages2IdGoods3  int    `elements:"name:pages_2_id_goods_3;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_3;type:integer;default:0;not null;" json:"pages_2_id_goods_3"`
	Pages2IdGoods4  int    `elements:"name:pages_2_id_goods_4;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_4;type:integer;default:0;not null;" json:"pages_2_id_goods_4"`
	Pages2IdGoods5  int    `elements:"name:pages_2_id_goods_5;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_5;type:integer;default:0;not null;" json:"pages_2_id_goods_5"`
	Pages2IdGoods6  int    `elements:"name:pages_2_id_goods_6;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_6;type:integer;default:0;not null;" json:"pages_2_id_goods_6"`
	Pages2IdGoods7  int    `elements:"name:pages_2_id_goods_7;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_7;type:integer;default:0;not null;" json:"pages_2_id_goods_7"`
	Pages2IdGoods8  int    `elements:"name:pages_2_id_goods_8;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_8;type:integer;default:0;not null;" json:"pages_2_id_goods_8"`
	Pages2IdGoods9  int    `elements:"name:pages_2_id_goods_9;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_9;type:integer;default:0;not null;" json:"pages_2_id_goods_9"`
	Pages2IdGoods10 int    `elements:"name:pages_2_id_goods_10;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_10;type:integer;default:0;not null;" json:"pages_2_id_goods_10"`
	Pages2IdGoods11 int    `elements:"name:pages_2_id_goods_11;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_11;type:integer;default:0;not null;" json:"pages_2_id_goods_11"`
	Pages2IdGoods12 int    `elements:"name:pages_2_id_goods_12;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_12;type:integer;default:0;not null;" json:"pages_2_id_goods_12"`
	Pages2IdGoods13 int    `elements:"name:pages_2_id_goods_13;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_13;type:integer;default:0;not null;" json:"pages_2_id_goods_13"`
	Pages2IdGoods14 int    `elements:"name:pages_2_id_goods_14;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_14;type:integer;default:0;not null;" json:"pages_2_id_goods_14"`
	Pages2IdGoods15 int    `elements:"name:pages_2_id_goods_15;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_15;type:integer;default:0;not null;" json:"pages_2_id_goods_15"`
	Pages2IdGoods16 int    `elements:"name:pages_2_id_goods_16;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_16;type:integer;default:0;not null;" json:"pages_2_id_goods_16"`
	Pages2IdGoods17 int    `elements:"name:pages_2_id_goods_17;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_17;type:integer;default:0;not null;" json:"pages_2_id_goods_17"`
	Pages2IdGoods18 int    `elements:"name:pages_2_id_goods_18;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_18;type:integer;default:0;not null;" json:"pages_2_id_goods_18"`
	Pages2IdGoods19 int    `elements:"name:pages_2_id_goods_19;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_19;type:integer;default:0;not null;" json:"pages_2_id_goods_19"`
	Pages2IdGoods20 int    `elements:"name:pages_2_id_goods_20;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_20;type:integer;default:0;not null;" json:"pages_2_id_goods_20"`
	Pages2IdGoods21 int    `elements:"name:pages_2_id_goods_21;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_21;type:integer;default:0;not null;" json:"pages_2_id_goods_21"`
	Pages2IdGoods22 int    `elements:"name:pages_2_id_goods_22;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_22;type:integer;default:0;not null;" json:"pages_2_id_goods_22"`
	Pages2IdGoods23 int    `elements:"name:pages_2_id_goods_23;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_23;type:integer;default:0;not null;" json:"pages_2_id_goods_23"`
	Pages2IdGoods24 int    `elements:"name:pages_2_id_goods_24;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_24;type:integer;default:0;not null;" json:"pages_2_id_goods_24"`
	Pages2IdGoods25 int    `elements:"name:pages_2_id_goods_25;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_25;type:integer;default:0;not null;" json:"pages_2_id_goods_25"`
	Pages2IdGoods26 int    `elements:"name:pages_2_id_goods_26;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_26;type:integer;default:0;not null;" json:"pages_2_id_goods_26"`
	Pages2IdGoods27 int    `elements:"name:pages_2_id_goods_27;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_27;type:integer;default:0;not null;" json:"pages_2_id_goods_27"`
	Pages2IdGoods28 int    `elements:"name:pages_2_id_goods_28;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_28;type:integer;default:0;not null;" json:"pages_2_id_goods_28"`
	Pages2IdGoods29 int    `elements:"name:pages_2_id_goods_29;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_29;type:integer;default:0;not null;" json:"pages_2_id_goods_29"`
	Pages2IdGoods30 int    `elements:"name:pages_2_id_goods_30;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_30;type:integer;default:0;not null;" json:"pages_2_id_goods_30"`
	Pages2IdGoods31 int    `elements:"name:pages_2_id_goods_31;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_31;type:integer;default:0;not null;" json:"pages_2_id_goods_31"`
	Pages2IdGoods32 int    `elements:"name:pages_2_id_goods_32;type:int;size:4;text:未知;" gorm:"column:pages_2_id_goods_32;type:integer;default:0;not null;" json:"pages_2_id_goods_32"`
	Pages3PageTitle string `elements:"name:pages_3_page_title;type:unicode;size:16;text:未知;" gorm:"column:pages_3_page_title;type:varchar(16);not null;" json:"pages_3_page_title"`
	Pages3IdGoods1  int    `elements:"name:pages_3_id_goods_1;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_1;type:integer;default:0;not null;" json:"pages_3_id_goods_1"`
	Pages3IdGoods2  int    `elements:"name:pages_3_id_goods_2;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_2;type:integer;default:0;not null;" json:"pages_3_id_goods_2"`
	Pages3IdGoods3  int    `elements:"name:pages_3_id_goods_3;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_3;type:integer;default:0;not null;" json:"pages_3_id_goods_3"`
	Pages3IdGoods4  int    `elements:"name:pages_3_id_goods_4;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_4;type:integer;default:0;not null;" json:"pages_3_id_goods_4"`
	Pages3IdGoods5  int    `elements:"name:pages_3_id_goods_5;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_5;type:integer;default:0;not null;" json:"pages_3_id_goods_5"`
	Pages3IdGoods6  int    `elements:"name:pages_3_id_goods_6;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_6;type:integer;default:0;not null;" json:"pages_3_id_goods_6"`
	Pages3IdGoods7  int    `elements:"name:pages_3_id_goods_7;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_7;type:integer;default:0;not null;" json:"pages_3_id_goods_7"`
	Pages3IdGoods8  int    `elements:"name:pages_3_id_goods_8;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_8;type:integer;default:0;not null;" json:"pages_3_id_goods_8"`
	Pages3IdGoods9  int    `elements:"name:pages_3_id_goods_9;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_9;type:integer;default:0;not null;" json:"pages_3_id_goods_9"`
	Pages3IdGoods10 int    `elements:"name:pages_3_id_goods_10;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_10;type:integer;default:0;not null;" json:"pages_3_id_goods_10"`
	Pages3IdGoods11 int    `elements:"name:pages_3_id_goods_11;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_11;type:integer;default:0;not null;" json:"pages_3_id_goods_11"`
	Pages3IdGoods12 int    `elements:"name:pages_3_id_goods_12;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_12;type:integer;default:0;not null;" json:"pages_3_id_goods_12"`
	Pages3IdGoods13 int    `elements:"name:pages_3_id_goods_13;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_13;type:integer;default:0;not null;" json:"pages_3_id_goods_13"`
	Pages3IdGoods14 int    `elements:"name:pages_3_id_goods_14;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_14;type:integer;default:0;not null;" json:"pages_3_id_goods_14"`
	Pages3IdGoods15 int    `elements:"name:pages_3_id_goods_15;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_15;type:integer;default:0;not null;" json:"pages_3_id_goods_15"`
	Pages3IdGoods16 int    `elements:"name:pages_3_id_goods_16;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_16;type:integer;default:0;not null;" json:"pages_3_id_goods_16"`
	Pages3IdGoods17 int    `elements:"name:pages_3_id_goods_17;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_17;type:integer;default:0;not null;" json:"pages_3_id_goods_17"`
	Pages3IdGoods18 int    `elements:"name:pages_3_id_goods_18;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_18;type:integer;default:0;not null;" json:"pages_3_id_goods_18"`
	Pages3IdGoods19 int    `elements:"name:pages_3_id_goods_19;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_19;type:integer;default:0;not null;" json:"pages_3_id_goods_19"`
	Pages3IdGoods20 int    `elements:"name:pages_3_id_goods_20;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_20;type:integer;default:0;not null;" json:"pages_3_id_goods_20"`
	Pages3IdGoods21 int    `elements:"name:pages_3_id_goods_21;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_21;type:integer;default:0;not null;" json:"pages_3_id_goods_21"`
	Pages3IdGoods22 int    `elements:"name:pages_3_id_goods_22;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_22;type:integer;default:0;not null;" json:"pages_3_id_goods_22"`
	Pages3IdGoods23 int    `elements:"name:pages_3_id_goods_23;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_23;type:integer;default:0;not null;" json:"pages_3_id_goods_23"`
	Pages3IdGoods24 int    `elements:"name:pages_3_id_goods_24;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_24;type:integer;default:0;not null;" json:"pages_3_id_goods_24"`
	Pages3IdGoods25 int    `elements:"name:pages_3_id_goods_25;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_25;type:integer;default:0;not null;" json:"pages_3_id_goods_25"`
	Pages3IdGoods26 int    `elements:"name:pages_3_id_goods_26;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_26;type:integer;default:0;not null;" json:"pages_3_id_goods_26"`
	Pages3IdGoods27 int    `elements:"name:pages_3_id_goods_27;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_27;type:integer;default:0;not null;" json:"pages_3_id_goods_27"`
	Pages3IdGoods28 int    `elements:"name:pages_3_id_goods_28;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_28;type:integer;default:0;not null;" json:"pages_3_id_goods_28"`
	Pages3IdGoods29 int    `elements:"name:pages_3_id_goods_29;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_29;type:integer;default:0;not null;" json:"pages_3_id_goods_29"`
	Pages3IdGoods30 int    `elements:"name:pages_3_id_goods_30;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_30;type:integer;default:0;not null;" json:"pages_3_id_goods_30"`
	Pages3IdGoods31 int    `elements:"name:pages_3_id_goods_31;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_31;type:integer;default:0;not null;" json:"pages_3_id_goods_31"`
	Pages3IdGoods32 int    `elements:"name:pages_3_id_goods_32;type:int;size:4;text:未知;" gorm:"column:pages_3_id_goods_32;type:integer;default:0;not null;" json:"pages_3_id_goods_32"`
	Pages4PageTitle string `elements:"name:pages_4_page_title;type:unicode;size:16;text:未知;" gorm:"column:pages_4_page_title;type:varchar(16);not null;" json:"pages_4_page_title"`
	Pages4IdGoods1  int    `elements:"name:pages_4_id_goods_1;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_1;type:integer;default:0;not null;" json:"pages_4_id_goods_1"`
	Pages4IdGoods2  int    `elements:"name:pages_4_id_goods_2;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_2;type:integer;default:0;not null;" json:"pages_4_id_goods_2"`
	Pages4IdGoods3  int    `elements:"name:pages_4_id_goods_3;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_3;type:integer;default:0;not null;" json:"pages_4_id_goods_3"`
	Pages4IdGoods4  int    `elements:"name:pages_4_id_goods_4;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_4;type:integer;default:0;not null;" json:"pages_4_id_goods_4"`
	Pages4IdGoods5  int    `elements:"name:pages_4_id_goods_5;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_5;type:integer;default:0;not null;" json:"pages_4_id_goods_5"`
	Pages4IdGoods6  int    `elements:"name:pages_4_id_goods_6;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_6;type:integer;default:0;not null;" json:"pages_4_id_goods_6"`
	Pages4IdGoods7  int    `elements:"name:pages_4_id_goods_7;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_7;type:integer;default:0;not null;" json:"pages_4_id_goods_7"`
	Pages4IdGoods8  int    `elements:"name:pages_4_id_goods_8;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_8;type:integer;default:0;not null;" json:"pages_4_id_goods_8"`
	Pages4IdGoods9  int    `elements:"name:pages_4_id_goods_9;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_9;type:integer;default:0;not null;" json:"pages_4_id_goods_9"`
	Pages4IdGoods10 int    `elements:"name:pages_4_id_goods_10;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_10;type:integer;default:0;not null;" json:"pages_4_id_goods_10"`
	Pages4IdGoods11 int    `elements:"name:pages_4_id_goods_11;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_11;type:integer;default:0;not null;" json:"pages_4_id_goods_11"`
	Pages4IdGoods12 int    `elements:"name:pages_4_id_goods_12;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_12;type:integer;default:0;not null;" json:"pages_4_id_goods_12"`
	Pages4IdGoods13 int    `elements:"name:pages_4_id_goods_13;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_13;type:integer;default:0;not null;" json:"pages_4_id_goods_13"`
	Pages4IdGoods14 int    `elements:"name:pages_4_id_goods_14;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_14;type:integer;default:0;not null;" json:"pages_4_id_goods_14"`
	Pages4IdGoods15 int    `elements:"name:pages_4_id_goods_15;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_15;type:integer;default:0;not null;" json:"pages_4_id_goods_15"`
	Pages4IdGoods16 int    `elements:"name:pages_4_id_goods_16;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_16;type:integer;default:0;not null;" json:"pages_4_id_goods_16"`
	Pages4IdGoods17 int    `elements:"name:pages_4_id_goods_17;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_17;type:integer;default:0;not null;" json:"pages_4_id_goods_17"`
	Pages4IdGoods18 int    `elements:"name:pages_4_id_goods_18;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_18;type:integer;default:0;not null;" json:"pages_4_id_goods_18"`
	Pages4IdGoods19 int    `elements:"name:pages_4_id_goods_19;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_19;type:integer;default:0;not null;" json:"pages_4_id_goods_19"`
	Pages4IdGoods20 int    `elements:"name:pages_4_id_goods_20;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_20;type:integer;default:0;not null;" json:"pages_4_id_goods_20"`
	Pages4IdGoods21 int    `elements:"name:pages_4_id_goods_21;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_21;type:integer;default:0;not null;" json:"pages_4_id_goods_21"`
	Pages4IdGoods22 int    `elements:"name:pages_4_id_goods_22;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_22;type:integer;default:0;not null;" json:"pages_4_id_goods_22"`
	Pages4IdGoods23 int    `elements:"name:pages_4_id_goods_23;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_23;type:integer;default:0;not null;" json:"pages_4_id_goods_23"`
	Pages4IdGoods24 int    `elements:"name:pages_4_id_goods_24;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_24;type:integer;default:0;not null;" json:"pages_4_id_goods_24"`
	Pages4IdGoods25 int    `elements:"name:pages_4_id_goods_25;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_25;type:integer;default:0;not null;" json:"pages_4_id_goods_25"`
	Pages4IdGoods26 int    `elements:"name:pages_4_id_goods_26;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_26;type:integer;default:0;not null;" json:"pages_4_id_goods_26"`
	Pages4IdGoods27 int    `elements:"name:pages_4_id_goods_27;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_27;type:integer;default:0;not null;" json:"pages_4_id_goods_27"`
	Pages4IdGoods28 int    `elements:"name:pages_4_id_goods_28;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_28;type:integer;default:0;not null;" json:"pages_4_id_goods_28"`
	Pages4IdGoods29 int    `elements:"name:pages_4_id_goods_29;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_29;type:integer;default:0;not null;" json:"pages_4_id_goods_29"`
	Pages4IdGoods30 int    `elements:"name:pages_4_id_goods_30;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_30;type:integer;default:0;not null;" json:"pages_4_id_goods_30"`
	Pages4IdGoods31 int    `elements:"name:pages_4_id_goods_31;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_31;type:integer;default:0;not null;" json:"pages_4_id_goods_31"`
	Pages4IdGoods32 int    `elements:"name:pages_4_id_goods_32;type:int;size:4;text:未知;" gorm:"column:pages_4_id_goods_32;type:integer;default:0;not null;" json:"pages_4_id_goods_32"`
	Pages5PageTitle string `elements:"name:pages_5_page_title;type:unicode;size:16;text:未知;" gorm:"column:pages_5_page_title;type:varchar(16);not null;" json:"pages_5_page_title"`
	Pages5IdGoods1  int    `elements:"name:pages_5_id_goods_1;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_1;type:integer;default:0;not null;" json:"pages_5_id_goods_1"`
	Pages5IdGoods2  int    `elements:"name:pages_5_id_goods_2;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_2;type:integer;default:0;not null;" json:"pages_5_id_goods_2"`
	Pages5IdGoods3  int    `elements:"name:pages_5_id_goods_3;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_3;type:integer;default:0;not null;" json:"pages_5_id_goods_3"`
	Pages5IdGoods4  int    `elements:"name:pages_5_id_goods_4;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_4;type:integer;default:0;not null;" json:"pages_5_id_goods_4"`
	Pages5IdGoods5  int    `elements:"name:pages_5_id_goods_5;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_5;type:integer;default:0;not null;" json:"pages_5_id_goods_5"`
	Pages5IdGoods6  int    `elements:"name:pages_5_id_goods_6;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_6;type:integer;default:0;not null;" json:"pages_5_id_goods_6"`
	Pages5IdGoods7  int    `elements:"name:pages_5_id_goods_7;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_7;type:integer;default:0;not null;" json:"pages_5_id_goods_7"`
	Pages5IdGoods8  int    `elements:"name:pages_5_id_goods_8;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_8;type:integer;default:0;not null;" json:"pages_5_id_goods_8"`
	Pages5IdGoods9  int    `elements:"name:pages_5_id_goods_9;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_9;type:integer;default:0;not null;" json:"pages_5_id_goods_9"`
	Pages5IdGoods10 int    `elements:"name:pages_5_id_goods_10;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_10;type:integer;default:0;not null;" json:"pages_5_id_goods_10"`
	Pages5IdGoods11 int    `elements:"name:pages_5_id_goods_11;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_11;type:integer;default:0;not null;" json:"pages_5_id_goods_11"`
	Pages5IdGoods12 int    `elements:"name:pages_5_id_goods_12;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_12;type:integer;default:0;not null;" json:"pages_5_id_goods_12"`
	Pages5IdGoods13 int    `elements:"name:pages_5_id_goods_13;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_13;type:integer;default:0;not null;" json:"pages_5_id_goods_13"`
	Pages5IdGoods14 int    `elements:"name:pages_5_id_goods_14;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_14;type:integer;default:0;not null;" json:"pages_5_id_goods_14"`
	Pages5IdGoods15 int    `elements:"name:pages_5_id_goods_15;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_15;type:integer;default:0;not null;" json:"pages_5_id_goods_15"`
	Pages5IdGoods16 int    `elements:"name:pages_5_id_goods_16;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_16;type:integer;default:0;not null;" json:"pages_5_id_goods_16"`
	Pages5IdGoods17 int    `elements:"name:pages_5_id_goods_17;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_17;type:integer;default:0;not null;" json:"pages_5_id_goods_17"`
	Pages5IdGoods18 int    `elements:"name:pages_5_id_goods_18;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_18;type:integer;default:0;not null;" json:"pages_5_id_goods_18"`
	Pages5IdGoods19 int    `elements:"name:pages_5_id_goods_19;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_19;type:integer;default:0;not null;" json:"pages_5_id_goods_19"`
	Pages5IdGoods20 int    `elements:"name:pages_5_id_goods_20;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_20;type:integer;default:0;not null;" json:"pages_5_id_goods_20"`
	Pages5IdGoods21 int    `elements:"name:pages_5_id_goods_21;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_21;type:integer;default:0;not null;" json:"pages_5_id_goods_21"`
	Pages5IdGoods22 int    `elements:"name:pages_5_id_goods_22;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_22;type:integer;default:0;not null;" json:"pages_5_id_goods_22"`
	Pages5IdGoods23 int    `elements:"name:pages_5_id_goods_23;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_23;type:integer;default:0;not null;" json:"pages_5_id_goods_23"`
	Pages5IdGoods24 int    `elements:"name:pages_5_id_goods_24;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_24;type:integer;default:0;not null;" json:"pages_5_id_goods_24"`
	Pages5IdGoods25 int    `elements:"name:pages_5_id_goods_25;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_25;type:integer;default:0;not null;" json:"pages_5_id_goods_25"`
	Pages5IdGoods26 int    `elements:"name:pages_5_id_goods_26;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_26;type:integer;default:0;not null;" json:"pages_5_id_goods_26"`
	Pages5IdGoods27 int    `elements:"name:pages_5_id_goods_27;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_27;type:integer;default:0;not null;" json:"pages_5_id_goods_27"`
	Pages5IdGoods28 int    `elements:"name:pages_5_id_goods_28;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_28;type:integer;default:0;not null;" json:"pages_5_id_goods_28"`
	Pages5IdGoods29 int    `elements:"name:pages_5_id_goods_29;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_29;type:integer;default:0;not null;" json:"pages_5_id_goods_29"`
	Pages5IdGoods30 int    `elements:"name:pages_5_id_goods_30;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_30;type:integer;default:0;not null;" json:"pages_5_id_goods_30"`
	Pages5IdGoods31 int    `elements:"name:pages_5_id_goods_31;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_31;type:integer;default:0;not null;" json:"pages_5_id_goods_31"`
	Pages5IdGoods32 int    `elements:"name:pages_5_id_goods_32;type:int;size:4;text:未知;" gorm:"column:pages_5_id_goods_32;type:integer;default:0;not null;" json:"pages_5_id_goods_32"`
	Pages6PageTitle string `elements:"name:pages_6_page_title;type:unicode;size:16;text:未知;" gorm:"column:pages_6_page_title;type:varchar(16);not null;" json:"pages_6_page_title"`
	Pages6IdGoods1  int    `elements:"name:pages_6_id_goods_1;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_1;type:integer;default:0;not null;" json:"pages_6_id_goods_1"`
	Pages6IdGoods2  int    `elements:"name:pages_6_id_goods_2;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_2;type:integer;default:0;not null;" json:"pages_6_id_goods_2"`
	Pages6IdGoods3  int    `elements:"name:pages_6_id_goods_3;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_3;type:integer;default:0;not null;" json:"pages_6_id_goods_3"`
	Pages6IdGoods4  int    `elements:"name:pages_6_id_goods_4;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_4;type:integer;default:0;not null;" json:"pages_6_id_goods_4"`
	Pages6IdGoods5  int    `elements:"name:pages_6_id_goods_5;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_5;type:integer;default:0;not null;" json:"pages_6_id_goods_5"`
	Pages6IdGoods6  int    `elements:"name:pages_6_id_goods_6;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_6;type:integer;default:0;not null;" json:"pages_6_id_goods_6"`
	Pages6IdGoods7  int    `elements:"name:pages_6_id_goods_7;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_7;type:integer;default:0;not null;" json:"pages_6_id_goods_7"`
	Pages6IdGoods8  int    `elements:"name:pages_6_id_goods_8;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_8;type:integer;default:0;not null;" json:"pages_6_id_goods_8"`
	Pages6IdGoods9  int    `elements:"name:pages_6_id_goods_9;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_9;type:integer;default:0;not null;" json:"pages_6_id_goods_9"`
	Pages6IdGoods10 int    `elements:"name:pages_6_id_goods_10;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_10;type:integer;default:0;not null;" json:"pages_6_id_goods_10"`
	Pages6IdGoods11 int    `elements:"name:pages_6_id_goods_11;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_11;type:integer;default:0;not null;" json:"pages_6_id_goods_11"`
	Pages6IdGoods12 int    `elements:"name:pages_6_id_goods_12;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_12;type:integer;default:0;not null;" json:"pages_6_id_goods_12"`
	Pages6IdGoods13 int    `elements:"name:pages_6_id_goods_13;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_13;type:integer;default:0;not null;" json:"pages_6_id_goods_13"`
	Pages6IdGoods14 int    `elements:"name:pages_6_id_goods_14;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_14;type:integer;default:0;not null;" json:"pages_6_id_goods_14"`
	Pages6IdGoods15 int    `elements:"name:pages_6_id_goods_15;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_15;type:integer;default:0;not null;" json:"pages_6_id_goods_15"`
	Pages6IdGoods16 int    `elements:"name:pages_6_id_goods_16;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_16;type:integer;default:0;not null;" json:"pages_6_id_goods_16"`
	Pages6IdGoods17 int    `elements:"name:pages_6_id_goods_17;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_17;type:integer;default:0;not null;" json:"pages_6_id_goods_17"`
	Pages6IdGoods18 int    `elements:"name:pages_6_id_goods_18;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_18;type:integer;default:0;not null;" json:"pages_6_id_goods_18"`
	Pages6IdGoods19 int    `elements:"name:pages_6_id_goods_19;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_19;type:integer;default:0;not null;" json:"pages_6_id_goods_19"`
	Pages6IdGoods20 int    `elements:"name:pages_6_id_goods_20;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_20;type:integer;default:0;not null;" json:"pages_6_id_goods_20"`
	Pages6IdGoods21 int    `elements:"name:pages_6_id_goods_21;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_21;type:integer;default:0;not null;" json:"pages_6_id_goods_21"`
	Pages6IdGoods22 int    `elements:"name:pages_6_id_goods_22;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_22;type:integer;default:0;not null;" json:"pages_6_id_goods_22"`
	Pages6IdGoods23 int    `elements:"name:pages_6_id_goods_23;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_23;type:integer;default:0;not null;" json:"pages_6_id_goods_23"`
	Pages6IdGoods24 int    `elements:"name:pages_6_id_goods_24;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_24;type:integer;default:0;not null;" json:"pages_6_id_goods_24"`
	Pages6IdGoods25 int    `elements:"name:pages_6_id_goods_25;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_25;type:integer;default:0;not null;" json:"pages_6_id_goods_25"`
	Pages6IdGoods26 int    `elements:"name:pages_6_id_goods_26;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_26;type:integer;default:0;not null;" json:"pages_6_id_goods_26"`
	Pages6IdGoods27 int    `elements:"name:pages_6_id_goods_27;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_27;type:integer;default:0;not null;" json:"pages_6_id_goods_27"`
	Pages6IdGoods28 int    `elements:"name:pages_6_id_goods_28;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_28;type:integer;default:0;not null;" json:"pages_6_id_goods_28"`
	Pages6IdGoods29 int    `elements:"name:pages_6_id_goods_29;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_29;type:integer;default:0;not null;" json:"pages_6_id_goods_29"`
	Pages6IdGoods30 int    `elements:"name:pages_6_id_goods_30;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_30;type:integer;default:0;not null;" json:"pages_6_id_goods_30"`
	Pages6IdGoods31 int    `elements:"name:pages_6_id_goods_31;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_31;type:integer;default:0;not null;" json:"pages_6_id_goods_31"`
	Pages6IdGoods32 int    `elements:"name:pages_6_id_goods_32;type:int;size:4;text:未知;" gorm:"column:pages_6_id_goods_32;type:integer;default:0;not null;" json:"pages_6_id_goods_32"`
	Pages7PageTitle string `elements:"name:pages_7_page_title;type:unicode;size:16;text:未知;" gorm:"column:pages_7_page_title;type:varchar(16);not null;" json:"pages_7_page_title"`
	Pages7IdGoods1  int    `elements:"name:pages_7_id_goods_1;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_1;type:integer;default:0;not null;" json:"pages_7_id_goods_1"`
	Pages7IdGoods2  int    `elements:"name:pages_7_id_goods_2;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_2;type:integer;default:0;not null;" json:"pages_7_id_goods_2"`
	Pages7IdGoods3  int    `elements:"name:pages_7_id_goods_3;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_3;type:integer;default:0;not null;" json:"pages_7_id_goods_3"`
	Pages7IdGoods4  int    `elements:"name:pages_7_id_goods_4;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_4;type:integer;default:0;not null;" json:"pages_7_id_goods_4"`
	Pages7IdGoods5  int    `elements:"name:pages_7_id_goods_5;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_5;type:integer;default:0;not null;" json:"pages_7_id_goods_5"`
	Pages7IdGoods6  int    `elements:"name:pages_7_id_goods_6;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_6;type:integer;default:0;not null;" json:"pages_7_id_goods_6"`
	Pages7IdGoods7  int    `elements:"name:pages_7_id_goods_7;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_7;type:integer;default:0;not null;" json:"pages_7_id_goods_7"`
	Pages7IdGoods8  int    `elements:"name:pages_7_id_goods_8;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_8;type:integer;default:0;not null;" json:"pages_7_id_goods_8"`
	Pages7IdGoods9  int    `elements:"name:pages_7_id_goods_9;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_9;type:integer;default:0;not null;" json:"pages_7_id_goods_9"`
	Pages7IdGoods10 int    `elements:"name:pages_7_id_goods_10;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_10;type:integer;default:0;not null;" json:"pages_7_id_goods_10"`
	Pages7IdGoods11 int    `elements:"name:pages_7_id_goods_11;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_11;type:integer;default:0;not null;" json:"pages_7_id_goods_11"`
	Pages7IdGoods12 int    `elements:"name:pages_7_id_goods_12;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_12;type:integer;default:0;not null;" json:"pages_7_id_goods_12"`
	Pages7IdGoods13 int    `elements:"name:pages_7_id_goods_13;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_13;type:integer;default:0;not null;" json:"pages_7_id_goods_13"`
	Pages7IdGoods14 int    `elements:"name:pages_7_id_goods_14;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_14;type:integer;default:0;not null;" json:"pages_7_id_goods_14"`
	Pages7IdGoods15 int    `elements:"name:pages_7_id_goods_15;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_15;type:integer;default:0;not null;" json:"pages_7_id_goods_15"`
	Pages7IdGoods16 int    `elements:"name:pages_7_id_goods_16;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_16;type:integer;default:0;not null;" json:"pages_7_id_goods_16"`
	Pages7IdGoods17 int    `elements:"name:pages_7_id_goods_17;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_17;type:integer;default:0;not null;" json:"pages_7_id_goods_17"`
	Pages7IdGoods18 int    `elements:"name:pages_7_id_goods_18;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_18;type:integer;default:0;not null;" json:"pages_7_id_goods_18"`
	Pages7IdGoods19 int    `elements:"name:pages_7_id_goods_19;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_19;type:integer;default:0;not null;" json:"pages_7_id_goods_19"`
	Pages7IdGoods20 int    `elements:"name:pages_7_id_goods_20;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_20;type:integer;default:0;not null;" json:"pages_7_id_goods_20"`
	Pages7IdGoods21 int    `elements:"name:pages_7_id_goods_21;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_21;type:integer;default:0;not null;" json:"pages_7_id_goods_21"`
	Pages7IdGoods22 int    `elements:"name:pages_7_id_goods_22;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_22;type:integer;default:0;not null;" json:"pages_7_id_goods_22"`
	Pages7IdGoods23 int    `elements:"name:pages_7_id_goods_23;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_23;type:integer;default:0;not null;" json:"pages_7_id_goods_23"`
	Pages7IdGoods24 int    `elements:"name:pages_7_id_goods_24;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_24;type:integer;default:0;not null;" json:"pages_7_id_goods_24"`
	Pages7IdGoods25 int    `elements:"name:pages_7_id_goods_25;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_25;type:integer;default:0;not null;" json:"pages_7_id_goods_25"`
	Pages7IdGoods26 int    `elements:"name:pages_7_id_goods_26;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_26;type:integer;default:0;not null;" json:"pages_7_id_goods_26"`
	Pages7IdGoods27 int    `elements:"name:pages_7_id_goods_27;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_27;type:integer;default:0;not null;" json:"pages_7_id_goods_27"`
	Pages7IdGoods28 int    `elements:"name:pages_7_id_goods_28;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_28;type:integer;default:0;not null;" json:"pages_7_id_goods_28"`
	Pages7IdGoods29 int    `elements:"name:pages_7_id_goods_29;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_29;type:integer;default:0;not null;" json:"pages_7_id_goods_29"`
	Pages7IdGoods30 int    `elements:"name:pages_7_id_goods_30;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_30;type:integer;default:0;not null;" json:"pages_7_id_goods_30"`
	Pages7IdGoods31 int    `elements:"name:pages_7_id_goods_31;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_31;type:integer;default:0;not null;" json:"pages_7_id_goods_31"`
	Pages7IdGoods32 int    `elements:"name:pages_7_id_goods_32;type:int;size:4;text:未知;" gorm:"column:pages_7_id_goods_32;type:integer;default:0;not null;" json:"pages_7_id_goods_32"`
	Pages8PageTitle string `elements:"name:pages_8_page_title;type:unicode;size:16;text:未知;" gorm:"column:pages_8_page_title;type:varchar(16);not null;" json:"pages_8_page_title"`
	Pages8IdGoods1  int    `elements:"name:pages_8_id_goods_1;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_1;type:integer;default:0;not null;" json:"pages_8_id_goods_1"`
	Pages8IdGoods2  int    `elements:"name:pages_8_id_goods_2;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_2;type:integer;default:0;not null;" json:"pages_8_id_goods_2"`
	Pages8IdGoods3  int    `elements:"name:pages_8_id_goods_3;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_3;type:integer;default:0;not null;" json:"pages_8_id_goods_3"`
	Pages8IdGoods4  int    `elements:"name:pages_8_id_goods_4;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_4;type:integer;default:0;not null;" json:"pages_8_id_goods_4"`
	Pages8IdGoods5  int    `elements:"name:pages_8_id_goods_5;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_5;type:integer;default:0;not null;" json:"pages_8_id_goods_5"`
	Pages8IdGoods6  int    `elements:"name:pages_8_id_goods_6;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_6;type:integer;default:0;not null;" json:"pages_8_id_goods_6"`
	Pages8IdGoods7  int    `elements:"name:pages_8_id_goods_7;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_7;type:integer;default:0;not null;" json:"pages_8_id_goods_7"`
	Pages8IdGoods8  int    `elements:"name:pages_8_id_goods_8;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_8;type:integer;default:0;not null;" json:"pages_8_id_goods_8"`
	Pages8IdGoods9  int    `elements:"name:pages_8_id_goods_9;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_9;type:integer;default:0;not null;" json:"pages_8_id_goods_9"`
	Pages8IdGoods10 int    `elements:"name:pages_8_id_goods_10;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_10;type:integer;default:0;not null;" json:"pages_8_id_goods_10"`
	Pages8IdGoods11 int    `elements:"name:pages_8_id_goods_11;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_11;type:integer;default:0;not null;" json:"pages_8_id_goods_11"`
	Pages8IdGoods12 int    `elements:"name:pages_8_id_goods_12;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_12;type:integer;default:0;not null;" json:"pages_8_id_goods_12"`
	Pages8IdGoods13 int    `elements:"name:pages_8_id_goods_13;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_13;type:integer;default:0;not null;" json:"pages_8_id_goods_13"`
	Pages8IdGoods14 int    `elements:"name:pages_8_id_goods_14;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_14;type:integer;default:0;not null;" json:"pages_8_id_goods_14"`
	Pages8IdGoods15 int    `elements:"name:pages_8_id_goods_15;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_15;type:integer;default:0;not null;" json:"pages_8_id_goods_15"`
	Pages8IdGoods16 int    `elements:"name:pages_8_id_goods_16;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_16;type:integer;default:0;not null;" json:"pages_8_id_goods_16"`
	Pages8IdGoods17 int    `elements:"name:pages_8_id_goods_17;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_17;type:integer;default:0;not null;" json:"pages_8_id_goods_17"`
	Pages8IdGoods18 int    `elements:"name:pages_8_id_goods_18;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_18;type:integer;default:0;not null;" json:"pages_8_id_goods_18"`
	Pages8IdGoods19 int    `elements:"name:pages_8_id_goods_19;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_19;type:integer;default:0;not null;" json:"pages_8_id_goods_19"`
	Pages8IdGoods20 int    `elements:"name:pages_8_id_goods_20;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_20;type:integer;default:0;not null;" json:"pages_8_id_goods_20"`
	Pages8IdGoods21 int    `elements:"name:pages_8_id_goods_21;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_21;type:integer;default:0;not null;" json:"pages_8_id_goods_21"`
	Pages8IdGoods22 int    `elements:"name:pages_8_id_goods_22;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_22;type:integer;default:0;not null;" json:"pages_8_id_goods_22"`
	Pages8IdGoods23 int    `elements:"name:pages_8_id_goods_23;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_23;type:integer;default:0;not null;" json:"pages_8_id_goods_23"`
	Pages8IdGoods24 int    `elements:"name:pages_8_id_goods_24;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_24;type:integer;default:0;not null;" json:"pages_8_id_goods_24"`
	Pages8IdGoods25 int    `elements:"name:pages_8_id_goods_25;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_25;type:integer;default:0;not null;" json:"pages_8_id_goods_25"`
	Pages8IdGoods26 int    `elements:"name:pages_8_id_goods_26;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_26;type:integer;default:0;not null;" json:"pages_8_id_goods_26"`
	Pages8IdGoods27 int    `elements:"name:pages_8_id_goods_27;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_27;type:integer;default:0;not null;" json:"pages_8_id_goods_27"`
	Pages8IdGoods28 int    `elements:"name:pages_8_id_goods_28;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_28;type:integer;default:0;not null;" json:"pages_8_id_goods_28"`
	Pages8IdGoods29 int    `elements:"name:pages_8_id_goods_29;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_29;type:integer;default:0;not null;" json:"pages_8_id_goods_29"`
	Pages8IdGoods30 int    `elements:"name:pages_8_id_goods_30;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_30;type:integer;default:0;not null;" json:"pages_8_id_goods_30"`
	Pages8IdGoods31 int    `elements:"name:pages_8_id_goods_31;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_31;type:integer;default:0;not null;" json:"pages_8_id_goods_31"`
	Pages8IdGoods32 int    `elements:"name:pages_8_id_goods_32;type:int;size:4;text:未知;" gorm:"column:pages_8_id_goods_32;type:integer;default:0;not null;" json:"pages_8_id_goods_32"`
}

func (NpcMakeService) TableName() string {
	return "el_npcmakeservice"
}

func (e *NpcMakeService) GetSize() (size int, err error) {
	return structEx.GetSize(e)
}

func (e *NpcMakeService) SetData(data []byte) (err error) {
	return structEx.SetData(e, data)
}
