package elements

import (
	"pw_server/utils/structEx"
)

type NpcTaskMatterService struct {
	ID                           int    `elements:"name:id;type:int;size:4;text:未知;" gorm:"column:id;type:integer;autoIncrement:false;uniqueIndex;not null;" json:"id"`
	Name                         string `elements:"name:name;type:unicode;size:64;text:未知;" gorm:"column:name;type:varchar(64);not null;" json:"name"`
	Tasks1IdTask                 int    `elements:"name:tasks_1_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_1_id_task;type:integer;default:0;not null;" json:"tasks_1_id_task"`
	Tasks1TaksMatters1IdMatter   int    `elements:"name:tasks_1_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_1_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_1_taks_matters_1_id_matter"`
	Tasks1TaksMatters1NumMatter  int    `elements:"name:tasks_1_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_1_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_1_taks_matters_1_num_matter"`
	Tasks1TaksMatters2IdMatter   int    `elements:"name:tasks_1_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_1_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_1_taks_matters_2_id_matter"`
	Tasks1TaksMatters2NumMatter  int    `elements:"name:tasks_1_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_1_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_1_taks_matters_2_num_matter"`
	Tasks1TaksMatters3IdMatter   int    `elements:"name:tasks_1_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_1_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_1_taks_matters_3_id_matter"`
	Tasks1TaksMatters3NumMatter  int    `elements:"name:tasks_1_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_1_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_1_taks_matters_3_num_matter"`
	Tasks1TaksMatters4IdMatter   int    `elements:"name:tasks_1_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_1_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_1_taks_matters_4_id_matter"`
	Tasks1TaksMatters4NumMatter  int    `elements:"name:tasks_1_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_1_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_1_taks_matters_4_num_matter"`
	Tasks2IdTask                 int    `elements:"name:tasks_2_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_2_id_task;type:integer;default:0;not null;" json:"tasks_2_id_task"`
	Tasks2TaksMatters1IdMatter   int    `elements:"name:tasks_2_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_2_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_2_taks_matters_1_id_matter"`
	Tasks2TaksMatters1NumMatter  int    `elements:"name:tasks_2_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_2_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_2_taks_matters_1_num_matter"`
	Tasks2TaksMatters2IdMatter   int    `elements:"name:tasks_2_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_2_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_2_taks_matters_2_id_matter"`
	Tasks2TaksMatters2NumMatter  int    `elements:"name:tasks_2_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_2_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_2_taks_matters_2_num_matter"`
	Tasks2TaksMatters3IdMatter   int    `elements:"name:tasks_2_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_2_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_2_taks_matters_3_id_matter"`
	Tasks2TaksMatters3NumMatter  int    `elements:"name:tasks_2_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_2_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_2_taks_matters_3_num_matter"`
	Tasks2TaksMatters4IdMatter   int    `elements:"name:tasks_2_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_2_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_2_taks_matters_4_id_matter"`
	Tasks2TaksMatters4NumMatter  int    `elements:"name:tasks_2_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_2_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_2_taks_matters_4_num_matter"`
	Tasks3IdTask                 int    `elements:"name:tasks_3_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_3_id_task;type:integer;default:0;not null;" json:"tasks_3_id_task"`
	Tasks3TaksMatters1IdMatter   int    `elements:"name:tasks_3_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_3_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_3_taks_matters_1_id_matter"`
	Tasks3TaksMatters1NumMatter  int    `elements:"name:tasks_3_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_3_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_3_taks_matters_1_num_matter"`
	Tasks3TaksMatters2IdMatter   int    `elements:"name:tasks_3_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_3_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_3_taks_matters_2_id_matter"`
	Tasks3TaksMatters2NumMatter  int    `elements:"name:tasks_3_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_3_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_3_taks_matters_2_num_matter"`
	Tasks3TaksMatters3IdMatter   int    `elements:"name:tasks_3_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_3_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_3_taks_matters_3_id_matter"`
	Tasks3TaksMatters3NumMatter  int    `elements:"name:tasks_3_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_3_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_3_taks_matters_3_num_matter"`
	Tasks3TaksMatters4IdMatter   int    `elements:"name:tasks_3_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_3_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_3_taks_matters_4_id_matter"`
	Tasks3TaksMatters4NumMatter  int    `elements:"name:tasks_3_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_3_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_3_taks_matters_4_num_matter"`
	Tasks4IdTask                 int    `elements:"name:tasks_4_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_4_id_task;type:integer;default:0;not null;" json:"tasks_4_id_task"`
	Tasks4TaksMatters1IdMatter   int    `elements:"name:tasks_4_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_4_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_4_taks_matters_1_id_matter"`
	Tasks4TaksMatters1NumMatter  int    `elements:"name:tasks_4_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_4_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_4_taks_matters_1_num_matter"`
	Tasks4TaksMatters2IdMatter   int    `elements:"name:tasks_4_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_4_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_4_taks_matters_2_id_matter"`
	Tasks4TaksMatters2NumMatter  int    `elements:"name:tasks_4_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_4_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_4_taks_matters_2_num_matter"`
	Tasks4TaksMatters3IdMatter   int    `elements:"name:tasks_4_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_4_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_4_taks_matters_3_id_matter"`
	Tasks4TaksMatters3NumMatter  int    `elements:"name:tasks_4_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_4_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_4_taks_matters_3_num_matter"`
	Tasks4TaksMatters4IdMatter   int    `elements:"name:tasks_4_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_4_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_4_taks_matters_4_id_matter"`
	Tasks4TaksMatters4NumMatter  int    `elements:"name:tasks_4_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_4_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_4_taks_matters_4_num_matter"`
	Tasks5IdTask                 int    `elements:"name:tasks_5_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_5_id_task;type:integer;default:0;not null;" json:"tasks_5_id_task"`
	Tasks5TaksMatters1IdMatter   int    `elements:"name:tasks_5_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_5_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_5_taks_matters_1_id_matter"`
	Tasks5TaksMatters1NumMatter  int    `elements:"name:tasks_5_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_5_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_5_taks_matters_1_num_matter"`
	Tasks5TaksMatters2IdMatter   int    `elements:"name:tasks_5_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_5_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_5_taks_matters_2_id_matter"`
	Tasks5TaksMatters2NumMatter  int    `elements:"name:tasks_5_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_5_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_5_taks_matters_2_num_matter"`
	Tasks5TaksMatters3IdMatter   int    `elements:"name:tasks_5_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_5_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_5_taks_matters_3_id_matter"`
	Tasks5TaksMatters3NumMatter  int    `elements:"name:tasks_5_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_5_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_5_taks_matters_3_num_matter"`
	Tasks5TaksMatters4IdMatter   int    `elements:"name:tasks_5_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_5_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_5_taks_matters_4_id_matter"`
	Tasks5TaksMatters4NumMatter  int    `elements:"name:tasks_5_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_5_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_5_taks_matters_4_num_matter"`
	Tasks6IdTask                 int    `elements:"name:tasks_6_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_6_id_task;type:integer;default:0;not null;" json:"tasks_6_id_task"`
	Tasks6TaksMatters1IdMatter   int    `elements:"name:tasks_6_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_6_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_6_taks_matters_1_id_matter"`
	Tasks6TaksMatters1NumMatter  int    `elements:"name:tasks_6_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_6_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_6_taks_matters_1_num_matter"`
	Tasks6TaksMatters2IdMatter   int    `elements:"name:tasks_6_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_6_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_6_taks_matters_2_id_matter"`
	Tasks6TaksMatters2NumMatter  int    `elements:"name:tasks_6_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_6_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_6_taks_matters_2_num_matter"`
	Tasks6TaksMatters3IdMatter   int    `elements:"name:tasks_6_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_6_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_6_taks_matters_3_id_matter"`
	Tasks6TaksMatters3NumMatter  int    `elements:"name:tasks_6_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_6_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_6_taks_matters_3_num_matter"`
	Tasks6TaksMatters4IdMatter   int    `elements:"name:tasks_6_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_6_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_6_taks_matters_4_id_matter"`
	Tasks6TaksMatters4NumMatter  int    `elements:"name:tasks_6_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_6_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_6_taks_matters_4_num_matter"`
	Tasks7IdTask                 int    `elements:"name:tasks_7_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_7_id_task;type:integer;default:0;not null;" json:"tasks_7_id_task"`
	Tasks7TaksMatters1IdMatter   int    `elements:"name:tasks_7_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_7_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_7_taks_matters_1_id_matter"`
	Tasks7TaksMatters1NumMatter  int    `elements:"name:tasks_7_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_7_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_7_taks_matters_1_num_matter"`
	Tasks7TaksMatters2IdMatter   int    `elements:"name:tasks_7_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_7_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_7_taks_matters_2_id_matter"`
	Tasks7TaksMatters2NumMatter  int    `elements:"name:tasks_7_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_7_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_7_taks_matters_2_num_matter"`
	Tasks7TaksMatters3IdMatter   int    `elements:"name:tasks_7_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_7_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_7_taks_matters_3_id_matter"`
	Tasks7TaksMatters3NumMatter  int    `elements:"name:tasks_7_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_7_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_7_taks_matters_3_num_matter"`
	Tasks7TaksMatters4IdMatter   int    `elements:"name:tasks_7_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_7_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_7_taks_matters_4_id_matter"`
	Tasks7TaksMatters4NumMatter  int    `elements:"name:tasks_7_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_7_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_7_taks_matters_4_num_matter"`
	Tasks8IdTask                 int    `elements:"name:tasks_8_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_8_id_task;type:integer;default:0;not null;" json:"tasks_8_id_task"`
	Tasks8TaksMatters1IdMatter   int    `elements:"name:tasks_8_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_8_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_8_taks_matters_1_id_matter"`
	Tasks8TaksMatters1NumMatter  int    `elements:"name:tasks_8_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_8_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_8_taks_matters_1_num_matter"`
	Tasks8TaksMatters2IdMatter   int    `elements:"name:tasks_8_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_8_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_8_taks_matters_2_id_matter"`
	Tasks8TaksMatters2NumMatter  int    `elements:"name:tasks_8_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_8_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_8_taks_matters_2_num_matter"`
	Tasks8TaksMatters3IdMatter   int    `elements:"name:tasks_8_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_8_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_8_taks_matters_3_id_matter"`
	Tasks8TaksMatters3NumMatter  int    `elements:"name:tasks_8_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_8_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_8_taks_matters_3_num_matter"`
	Tasks8TaksMatters4IdMatter   int    `elements:"name:tasks_8_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_8_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_8_taks_matters_4_id_matter"`
	Tasks8TaksMatters4NumMatter  int    `elements:"name:tasks_8_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_8_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_8_taks_matters_4_num_matter"`
	Tasks9IdTask                 int    `elements:"name:tasks_9_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_9_id_task;type:integer;default:0;not null;" json:"tasks_9_id_task"`
	Tasks9TaksMatters1IdMatter   int    `elements:"name:tasks_9_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_9_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_9_taks_matters_1_id_matter"`
	Tasks9TaksMatters1NumMatter  int    `elements:"name:tasks_9_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_9_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_9_taks_matters_1_num_matter"`
	Tasks9TaksMatters2IdMatter   int    `elements:"name:tasks_9_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_9_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_9_taks_matters_2_id_matter"`
	Tasks9TaksMatters2NumMatter  int    `elements:"name:tasks_9_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_9_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_9_taks_matters_2_num_matter"`
	Tasks9TaksMatters3IdMatter   int    `elements:"name:tasks_9_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_9_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_9_taks_matters_3_id_matter"`
	Tasks9TaksMatters3NumMatter  int    `elements:"name:tasks_9_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_9_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_9_taks_matters_3_num_matter"`
	Tasks9TaksMatters4IdMatter   int    `elements:"name:tasks_9_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_9_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_9_taks_matters_4_id_matter"`
	Tasks9TaksMatters4NumMatter  int    `elements:"name:tasks_9_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_9_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_9_taks_matters_4_num_matter"`
	Tasks10IdTask                int    `elements:"name:tasks_10_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_10_id_task;type:integer;default:0;not null;" json:"tasks_10_id_task"`
	Tasks10TaksMatters1IdMatter  int    `elements:"name:tasks_10_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_10_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_10_taks_matters_1_id_matter"`
	Tasks10TaksMatters1NumMatter int    `elements:"name:tasks_10_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_10_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_10_taks_matters_1_num_matter"`
	Tasks10TaksMatters2IdMatter  int    `elements:"name:tasks_10_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_10_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_10_taks_matters_2_id_matter"`
	Tasks10TaksMatters2NumMatter int    `elements:"name:tasks_10_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_10_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_10_taks_matters_2_num_matter"`
	Tasks10TaksMatters3IdMatter  int    `elements:"name:tasks_10_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_10_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_10_taks_matters_3_id_matter"`
	Tasks10TaksMatters3NumMatter int    `elements:"name:tasks_10_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_10_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_10_taks_matters_3_num_matter"`
	Tasks10TaksMatters4IdMatter  int    `elements:"name:tasks_10_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_10_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_10_taks_matters_4_id_matter"`
	Tasks10TaksMatters4NumMatter int    `elements:"name:tasks_10_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_10_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_10_taks_matters_4_num_matter"`
	Tasks11IdTask                int    `elements:"name:tasks_11_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_11_id_task;type:integer;default:0;not null;" json:"tasks_11_id_task"`
	Tasks11TaksMatters1IdMatter  int    `elements:"name:tasks_11_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_11_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_11_taks_matters_1_id_matter"`
	Tasks11TaksMatters1NumMatter int    `elements:"name:tasks_11_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_11_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_11_taks_matters_1_num_matter"`
	Tasks11TaksMatters2IdMatter  int    `elements:"name:tasks_11_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_11_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_11_taks_matters_2_id_matter"`
	Tasks11TaksMatters2NumMatter int    `elements:"name:tasks_11_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_11_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_11_taks_matters_2_num_matter"`
	Tasks11TaksMatters3IdMatter  int    `elements:"name:tasks_11_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_11_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_11_taks_matters_3_id_matter"`
	Tasks11TaksMatters3NumMatter int    `elements:"name:tasks_11_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_11_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_11_taks_matters_3_num_matter"`
	Tasks11TaksMatters4IdMatter  int    `elements:"name:tasks_11_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_11_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_11_taks_matters_4_id_matter"`
	Tasks11TaksMatters4NumMatter int    `elements:"name:tasks_11_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_11_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_11_taks_matters_4_num_matter"`
	Tasks12IdTask                int    `elements:"name:tasks_12_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_12_id_task;type:integer;default:0;not null;" json:"tasks_12_id_task"`
	Tasks12TaksMatters1IdMatter  int    `elements:"name:tasks_12_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_12_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_12_taks_matters_1_id_matter"`
	Tasks12TaksMatters1NumMatter int    `elements:"name:tasks_12_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_12_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_12_taks_matters_1_num_matter"`
	Tasks12TaksMatters2IdMatter  int    `elements:"name:tasks_12_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_12_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_12_taks_matters_2_id_matter"`
	Tasks12TaksMatters2NumMatter int    `elements:"name:tasks_12_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_12_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_12_taks_matters_2_num_matter"`
	Tasks12TaksMatters3IdMatter  int    `elements:"name:tasks_12_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_12_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_12_taks_matters_3_id_matter"`
	Tasks12TaksMatters3NumMatter int    `elements:"name:tasks_12_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_12_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_12_taks_matters_3_num_matter"`
	Tasks12TaksMatters4IdMatter  int    `elements:"name:tasks_12_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_12_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_12_taks_matters_4_id_matter"`
	Tasks12TaksMatters4NumMatter int    `elements:"name:tasks_12_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_12_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_12_taks_matters_4_num_matter"`
	Tasks13IdTask                int    `elements:"name:tasks_13_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_13_id_task;type:integer;default:0;not null;" json:"tasks_13_id_task"`
	Tasks13TaksMatters1IdMatter  int    `elements:"name:tasks_13_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_13_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_13_taks_matters_1_id_matter"`
	Tasks13TaksMatters1NumMatter int    `elements:"name:tasks_13_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_13_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_13_taks_matters_1_num_matter"`
	Tasks13TaksMatters2IdMatter  int    `elements:"name:tasks_13_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_13_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_13_taks_matters_2_id_matter"`
	Tasks13TaksMatters2NumMatter int    `elements:"name:tasks_13_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_13_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_13_taks_matters_2_num_matter"`
	Tasks13TaksMatters3IdMatter  int    `elements:"name:tasks_13_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_13_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_13_taks_matters_3_id_matter"`
	Tasks13TaksMatters3NumMatter int    `elements:"name:tasks_13_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_13_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_13_taks_matters_3_num_matter"`
	Tasks13TaksMatters4IdMatter  int    `elements:"name:tasks_13_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_13_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_13_taks_matters_4_id_matter"`
	Tasks13TaksMatters4NumMatter int    `elements:"name:tasks_13_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_13_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_13_taks_matters_4_num_matter"`
	Tasks14IdTask                int    `elements:"name:tasks_14_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_14_id_task;type:integer;default:0;not null;" json:"tasks_14_id_task"`
	Tasks14TaksMatters1IdMatter  int    `elements:"name:tasks_14_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_14_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_14_taks_matters_1_id_matter"`
	Tasks14TaksMatters1NumMatter int    `elements:"name:tasks_14_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_14_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_14_taks_matters_1_num_matter"`
	Tasks14TaksMatters2IdMatter  int    `elements:"name:tasks_14_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_14_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_14_taks_matters_2_id_matter"`
	Tasks14TaksMatters2NumMatter int    `elements:"name:tasks_14_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_14_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_14_taks_matters_2_num_matter"`
	Tasks14TaksMatters3IdMatter  int    `elements:"name:tasks_14_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_14_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_14_taks_matters_3_id_matter"`
	Tasks14TaksMatters3NumMatter int    `elements:"name:tasks_14_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_14_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_14_taks_matters_3_num_matter"`
	Tasks14TaksMatters4IdMatter  int    `elements:"name:tasks_14_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_14_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_14_taks_matters_4_id_matter"`
	Tasks14TaksMatters4NumMatter int    `elements:"name:tasks_14_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_14_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_14_taks_matters_4_num_matter"`
	Tasks15IdTask                int    `elements:"name:tasks_15_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_15_id_task;type:integer;default:0;not null;" json:"tasks_15_id_task"`
	Tasks15TaksMatters1IdMatter  int    `elements:"name:tasks_15_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_15_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_15_taks_matters_1_id_matter"`
	Tasks15TaksMatters1NumMatter int    `elements:"name:tasks_15_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_15_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_15_taks_matters_1_num_matter"`
	Tasks15TaksMatters2IdMatter  int    `elements:"name:tasks_15_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_15_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_15_taks_matters_2_id_matter"`
	Tasks15TaksMatters2NumMatter int    `elements:"name:tasks_15_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_15_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_15_taks_matters_2_num_matter"`
	Tasks15TaksMatters3IdMatter  int    `elements:"name:tasks_15_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_15_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_15_taks_matters_3_id_matter"`
	Tasks15TaksMatters3NumMatter int    `elements:"name:tasks_15_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_15_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_15_taks_matters_3_num_matter"`
	Tasks15TaksMatters4IdMatter  int    `elements:"name:tasks_15_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_15_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_15_taks_matters_4_id_matter"`
	Tasks15TaksMatters4NumMatter int    `elements:"name:tasks_15_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_15_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_15_taks_matters_4_num_matter"`
	Tasks16IdTask                int    `elements:"name:tasks_16_id_task;type:int;size:4;text:未知;" gorm:"column:tasks_16_id_task;type:integer;default:0;not null;" json:"tasks_16_id_task"`
	Tasks16TaksMatters1IdMatter  int    `elements:"name:tasks_16_taks_matters_1_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_16_taks_matters_1_id_matter;type:integer;default:0;not null;" json:"tasks_16_taks_matters_1_id_matter"`
	Tasks16TaksMatters1NumMatter int    `elements:"name:tasks_16_taks_matters_1_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_16_taks_matters_1_num_matter;type:integer;default:0;not null;" json:"tasks_16_taks_matters_1_num_matter"`
	Tasks16TaksMatters2IdMatter  int    `elements:"name:tasks_16_taks_matters_2_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_16_taks_matters_2_id_matter;type:integer;default:0;not null;" json:"tasks_16_taks_matters_2_id_matter"`
	Tasks16TaksMatters2NumMatter int    `elements:"name:tasks_16_taks_matters_2_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_16_taks_matters_2_num_matter;type:integer;default:0;not null;" json:"tasks_16_taks_matters_2_num_matter"`
	Tasks16TaksMatters3IdMatter  int    `elements:"name:tasks_16_taks_matters_3_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_16_taks_matters_3_id_matter;type:integer;default:0;not null;" json:"tasks_16_taks_matters_3_id_matter"`
	Tasks16TaksMatters3NumMatter int    `elements:"name:tasks_16_taks_matters_3_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_16_taks_matters_3_num_matter;type:integer;default:0;not null;" json:"tasks_16_taks_matters_3_num_matter"`
	Tasks16TaksMatters4IdMatter  int    `elements:"name:tasks_16_taks_matters_4_id_matter;type:int;size:4;text:未知;" gorm:"column:tasks_16_taks_matters_4_id_matter;type:integer;default:0;not null;" json:"tasks_16_taks_matters_4_id_matter"`
	Tasks16TaksMatters4NumMatter int    `elements:"name:tasks_16_taks_matters_4_num_matter;type:int;size:4;text:未知;" gorm:"column:tasks_16_taks_matters_4_num_matter;type:integer;default:0;not null;" json:"tasks_16_taks_matters_4_num_matter"`
}

func (NpcTaskMatterService) TableName() string {
	return "el_npctaskmatterservice"
}

func (e *NpcTaskMatterService) GetSize() (size int, err error) {
	return structEx.GetSize(e)
}

func (e *NpcTaskMatterService) SetData(data []byte) (err error) {
	return structEx.SetData(e, data)
}
