package elements

import (
	"pw_server/utils/structEx"
)

type PlayerSecondlevelConfig struct {
	ID         int     `elements:"name:id;type:int;size:4;text:未知;" gorm:"column:id;type:integer;autoIncrement:false;uniqueIndex;not null;" json:"id"`
	Name       string  `elements:"name:name;type:unicode;size:64;text:未知;" gorm:"column:name;type:varchar(64);not null;" json:"name"`
	ExpLost1   float32 `elements:"name:exp_lost_1;type:float;size:4;text:未知;" gorm:"column:exp_lost_1;type:float;default:0;not null;" json:"exp_lost_1"`
	ExpLost2   float32 `elements:"name:exp_lost_2;type:float;size:4;text:未知;" gorm:"column:exp_lost_2;type:float;default:0;not null;" json:"exp_lost_2"`
	ExpLost3   float32 `elements:"name:exp_lost_3;type:float;size:4;text:未知;" gorm:"column:exp_lost_3;type:float;default:0;not null;" json:"exp_lost_3"`
	ExpLost4   float32 `elements:"name:exp_lost_4;type:float;size:4;text:未知;" gorm:"column:exp_lost_4;type:float;default:0;not null;" json:"exp_lost_4"`
	ExpLost5   float32 `elements:"name:exp_lost_5;type:float;size:4;text:未知;" gorm:"column:exp_lost_5;type:float;default:0;not null;" json:"exp_lost_5"`
	ExpLost6   float32 `elements:"name:exp_lost_6;type:float;size:4;text:未知;" gorm:"column:exp_lost_6;type:float;default:0;not null;" json:"exp_lost_6"`
	ExpLost7   float32 `elements:"name:exp_lost_7;type:float;size:4;text:未知;" gorm:"column:exp_lost_7;type:float;default:0;not null;" json:"exp_lost_7"`
	ExpLost8   float32 `elements:"name:exp_lost_8;type:float;size:4;text:未知;" gorm:"column:exp_lost_8;type:float;default:0;not null;" json:"exp_lost_8"`
	ExpLost9   float32 `elements:"name:exp_lost_9;type:float;size:4;text:未知;" gorm:"column:exp_lost_9;type:float;default:0;not null;" json:"exp_lost_9"`
	ExpLost10  float32 `elements:"name:exp_lost_10;type:float;size:4;text:未知;" gorm:"column:exp_lost_10;type:float;default:0;not null;" json:"exp_lost_10"`
	ExpLost11  float32 `elements:"name:exp_lost_11;type:float;size:4;text:未知;" gorm:"column:exp_lost_11;type:float;default:0;not null;" json:"exp_lost_11"`
	ExpLost12  float32 `elements:"name:exp_lost_12;type:float;size:4;text:未知;" gorm:"column:exp_lost_12;type:float;default:0;not null;" json:"exp_lost_12"`
	ExpLost13  float32 `elements:"name:exp_lost_13;type:float;size:4;text:未知;" gorm:"column:exp_lost_13;type:float;default:0;not null;" json:"exp_lost_13"`
	ExpLost14  float32 `elements:"name:exp_lost_14;type:float;size:4;text:未知;" gorm:"column:exp_lost_14;type:float;default:0;not null;" json:"exp_lost_14"`
	ExpLost15  float32 `elements:"name:exp_lost_15;type:float;size:4;text:未知;" gorm:"column:exp_lost_15;type:float;default:0;not null;" json:"exp_lost_15"`
	ExpLost16  float32 `elements:"name:exp_lost_16;type:float;size:4;text:未知;" gorm:"column:exp_lost_16;type:float;default:0;not null;" json:"exp_lost_16"`
	ExpLost17  float32 `elements:"name:exp_lost_17;type:float;size:4;text:未知;" gorm:"column:exp_lost_17;type:float;default:0;not null;" json:"exp_lost_17"`
	ExpLost18  float32 `elements:"name:exp_lost_18;type:float;size:4;text:未知;" gorm:"column:exp_lost_18;type:float;default:0;not null;" json:"exp_lost_18"`
	ExpLost19  float32 `elements:"name:exp_lost_19;type:float;size:4;text:未知;" gorm:"column:exp_lost_19;type:float;default:0;not null;" json:"exp_lost_19"`
	ExpLost20  float32 `elements:"name:exp_lost_20;type:float;size:4;text:未知;" gorm:"column:exp_lost_20;type:float;default:0;not null;" json:"exp_lost_20"`
	ExpLost21  float32 `elements:"name:exp_lost_21;type:float;size:4;text:未知;" gorm:"column:exp_lost_21;type:float;default:0;not null;" json:"exp_lost_21"`
	ExpLost22  float32 `elements:"name:exp_lost_22;type:float;size:4;text:未知;" gorm:"column:exp_lost_22;type:float;default:0;not null;" json:"exp_lost_22"`
	ExpLost23  float32 `elements:"name:exp_lost_23;type:float;size:4;text:未知;" gorm:"column:exp_lost_23;type:float;default:0;not null;" json:"exp_lost_23"`
	ExpLost24  float32 `elements:"name:exp_lost_24;type:float;size:4;text:未知;" gorm:"column:exp_lost_24;type:float;default:0;not null;" json:"exp_lost_24"`
	ExpLost25  float32 `elements:"name:exp_lost_25;type:float;size:4;text:未知;" gorm:"column:exp_lost_25;type:float;default:0;not null;" json:"exp_lost_25"`
	ExpLost26  float32 `elements:"name:exp_lost_26;type:float;size:4;text:未知;" gorm:"column:exp_lost_26;type:float;default:0;not null;" json:"exp_lost_26"`
	ExpLost27  float32 `elements:"name:exp_lost_27;type:float;size:4;text:未知;" gorm:"column:exp_lost_27;type:float;default:0;not null;" json:"exp_lost_27"`
	ExpLost28  float32 `elements:"name:exp_lost_28;type:float;size:4;text:未知;" gorm:"column:exp_lost_28;type:float;default:0;not null;" json:"exp_lost_28"`
	ExpLost29  float32 `elements:"name:exp_lost_29;type:float;size:4;text:未知;" gorm:"column:exp_lost_29;type:float;default:0;not null;" json:"exp_lost_29"`
	ExpLost30  float32 `elements:"name:exp_lost_30;type:float;size:4;text:未知;" gorm:"column:exp_lost_30;type:float;default:0;not null;" json:"exp_lost_30"`
	ExpLost31  float32 `elements:"name:exp_lost_31;type:float;size:4;text:未知;" gorm:"column:exp_lost_31;type:float;default:0;not null;" json:"exp_lost_31"`
	ExpLost32  float32 `elements:"name:exp_lost_32;type:float;size:4;text:未知;" gorm:"column:exp_lost_32;type:float;default:0;not null;" json:"exp_lost_32"`
	ExpLost33  float32 `elements:"name:exp_lost_33;type:float;size:4;text:未知;" gorm:"column:exp_lost_33;type:float;default:0;not null;" json:"exp_lost_33"`
	ExpLost34  float32 `elements:"name:exp_lost_34;type:float;size:4;text:未知;" gorm:"column:exp_lost_34;type:float;default:0;not null;" json:"exp_lost_34"`
	ExpLost35  float32 `elements:"name:exp_lost_35;type:float;size:4;text:未知;" gorm:"column:exp_lost_35;type:float;default:0;not null;" json:"exp_lost_35"`
	ExpLost36  float32 `elements:"name:exp_lost_36;type:float;size:4;text:未知;" gorm:"column:exp_lost_36;type:float;default:0;not null;" json:"exp_lost_36"`
	ExpLost37  float32 `elements:"name:exp_lost_37;type:float;size:4;text:未知;" gorm:"column:exp_lost_37;type:float;default:0;not null;" json:"exp_lost_37"`
	ExpLost38  float32 `elements:"name:exp_lost_38;type:float;size:4;text:未知;" gorm:"column:exp_lost_38;type:float;default:0;not null;" json:"exp_lost_38"`
	ExpLost39  float32 `elements:"name:exp_lost_39;type:float;size:4;text:未知;" gorm:"column:exp_lost_39;type:float;default:0;not null;" json:"exp_lost_39"`
	ExpLost40  float32 `elements:"name:exp_lost_40;type:float;size:4;text:未知;" gorm:"column:exp_lost_40;type:float;default:0;not null;" json:"exp_lost_40"`
	ExpLost41  float32 `elements:"name:exp_lost_41;type:float;size:4;text:未知;" gorm:"column:exp_lost_41;type:float;default:0;not null;" json:"exp_lost_41"`
	ExpLost42  float32 `elements:"name:exp_lost_42;type:float;size:4;text:未知;" gorm:"column:exp_lost_42;type:float;default:0;not null;" json:"exp_lost_42"`
	ExpLost43  float32 `elements:"name:exp_lost_43;type:float;size:4;text:未知;" gorm:"column:exp_lost_43;type:float;default:0;not null;" json:"exp_lost_43"`
	ExpLost44  float32 `elements:"name:exp_lost_44;type:float;size:4;text:未知;" gorm:"column:exp_lost_44;type:float;default:0;not null;" json:"exp_lost_44"`
	ExpLost45  float32 `elements:"name:exp_lost_45;type:float;size:4;text:未知;" gorm:"column:exp_lost_45;type:float;default:0;not null;" json:"exp_lost_45"`
	ExpLost46  float32 `elements:"name:exp_lost_46;type:float;size:4;text:未知;" gorm:"column:exp_lost_46;type:float;default:0;not null;" json:"exp_lost_46"`
	ExpLost47  float32 `elements:"name:exp_lost_47;type:float;size:4;text:未知;" gorm:"column:exp_lost_47;type:float;default:0;not null;" json:"exp_lost_47"`
	ExpLost48  float32 `elements:"name:exp_lost_48;type:float;size:4;text:未知;" gorm:"column:exp_lost_48;type:float;default:0;not null;" json:"exp_lost_48"`
	ExpLost49  float32 `elements:"name:exp_lost_49;type:float;size:4;text:未知;" gorm:"column:exp_lost_49;type:float;default:0;not null;" json:"exp_lost_49"`
	ExpLost50  float32 `elements:"name:exp_lost_50;type:float;size:4;text:未知;" gorm:"column:exp_lost_50;type:float;default:0;not null;" json:"exp_lost_50"`
	ExpLost51  float32 `elements:"name:exp_lost_51;type:float;size:4;text:未知;" gorm:"column:exp_lost_51;type:float;default:0;not null;" json:"exp_lost_51"`
	ExpLost52  float32 `elements:"name:exp_lost_52;type:float;size:4;text:未知;" gorm:"column:exp_lost_52;type:float;default:0;not null;" json:"exp_lost_52"`
	ExpLost53  float32 `elements:"name:exp_lost_53;type:float;size:4;text:未知;" gorm:"column:exp_lost_53;type:float;default:0;not null;" json:"exp_lost_53"`
	ExpLost54  float32 `elements:"name:exp_lost_54;type:float;size:4;text:未知;" gorm:"column:exp_lost_54;type:float;default:0;not null;" json:"exp_lost_54"`
	ExpLost55  float32 `elements:"name:exp_lost_55;type:float;size:4;text:未知;" gorm:"column:exp_lost_55;type:float;default:0;not null;" json:"exp_lost_55"`
	ExpLost56  float32 `elements:"name:exp_lost_56;type:float;size:4;text:未知;" gorm:"column:exp_lost_56;type:float;default:0;not null;" json:"exp_lost_56"`
	ExpLost57  float32 `elements:"name:exp_lost_57;type:float;size:4;text:未知;" gorm:"column:exp_lost_57;type:float;default:0;not null;" json:"exp_lost_57"`
	ExpLost58  float32 `elements:"name:exp_lost_58;type:float;size:4;text:未知;" gorm:"column:exp_lost_58;type:float;default:0;not null;" json:"exp_lost_58"`
	ExpLost59  float32 `elements:"name:exp_lost_59;type:float;size:4;text:未知;" gorm:"column:exp_lost_59;type:float;default:0;not null;" json:"exp_lost_59"`
	ExpLost60  float32 `elements:"name:exp_lost_60;type:float;size:4;text:未知;" gorm:"column:exp_lost_60;type:float;default:0;not null;" json:"exp_lost_60"`
	ExpLost61  float32 `elements:"name:exp_lost_61;type:float;size:4;text:未知;" gorm:"column:exp_lost_61;type:float;default:0;not null;" json:"exp_lost_61"`
	ExpLost62  float32 `elements:"name:exp_lost_62;type:float;size:4;text:未知;" gorm:"column:exp_lost_62;type:float;default:0;not null;" json:"exp_lost_62"`
	ExpLost63  float32 `elements:"name:exp_lost_63;type:float;size:4;text:未知;" gorm:"column:exp_lost_63;type:float;default:0;not null;" json:"exp_lost_63"`
	ExpLost64  float32 `elements:"name:exp_lost_64;type:float;size:4;text:未知;" gorm:"column:exp_lost_64;type:float;default:0;not null;" json:"exp_lost_64"`
	ExpLost65  float32 `elements:"name:exp_lost_65;type:float;size:4;text:未知;" gorm:"column:exp_lost_65;type:float;default:0;not null;" json:"exp_lost_65"`
	ExpLost66  float32 `elements:"name:exp_lost_66;type:float;size:4;text:未知;" gorm:"column:exp_lost_66;type:float;default:0;not null;" json:"exp_lost_66"`
	ExpLost67  float32 `elements:"name:exp_lost_67;type:float;size:4;text:未知;" gorm:"column:exp_lost_67;type:float;default:0;not null;" json:"exp_lost_67"`
	ExpLost68  float32 `elements:"name:exp_lost_68;type:float;size:4;text:未知;" gorm:"column:exp_lost_68;type:float;default:0;not null;" json:"exp_lost_68"`
	ExpLost69  float32 `elements:"name:exp_lost_69;type:float;size:4;text:未知;" gorm:"column:exp_lost_69;type:float;default:0;not null;" json:"exp_lost_69"`
	ExpLost70  float32 `elements:"name:exp_lost_70;type:float;size:4;text:未知;" gorm:"column:exp_lost_70;type:float;default:0;not null;" json:"exp_lost_70"`
	ExpLost71  float32 `elements:"name:exp_lost_71;type:float;size:4;text:未知;" gorm:"column:exp_lost_71;type:float;default:0;not null;" json:"exp_lost_71"`
	ExpLost72  float32 `elements:"name:exp_lost_72;type:float;size:4;text:未知;" gorm:"column:exp_lost_72;type:float;default:0;not null;" json:"exp_lost_72"`
	ExpLost73  float32 `elements:"name:exp_lost_73;type:float;size:4;text:未知;" gorm:"column:exp_lost_73;type:float;default:0;not null;" json:"exp_lost_73"`
	ExpLost74  float32 `elements:"name:exp_lost_74;type:float;size:4;text:未知;" gorm:"column:exp_lost_74;type:float;default:0;not null;" json:"exp_lost_74"`
	ExpLost75  float32 `elements:"name:exp_lost_75;type:float;size:4;text:未知;" gorm:"column:exp_lost_75;type:float;default:0;not null;" json:"exp_lost_75"`
	ExpLost76  float32 `elements:"name:exp_lost_76;type:float;size:4;text:未知;" gorm:"column:exp_lost_76;type:float;default:0;not null;" json:"exp_lost_76"`
	ExpLost77  float32 `elements:"name:exp_lost_77;type:float;size:4;text:未知;" gorm:"column:exp_lost_77;type:float;default:0;not null;" json:"exp_lost_77"`
	ExpLost78  float32 `elements:"name:exp_lost_78;type:float;size:4;text:未知;" gorm:"column:exp_lost_78;type:float;default:0;not null;" json:"exp_lost_78"`
	ExpLost79  float32 `elements:"name:exp_lost_79;type:float;size:4;text:未知;" gorm:"column:exp_lost_79;type:float;default:0;not null;" json:"exp_lost_79"`
	ExpLost80  float32 `elements:"name:exp_lost_80;type:float;size:4;text:未知;" gorm:"column:exp_lost_80;type:float;default:0;not null;" json:"exp_lost_80"`
	ExpLost81  float32 `elements:"name:exp_lost_81;type:float;size:4;text:未知;" gorm:"column:exp_lost_81;type:float;default:0;not null;" json:"exp_lost_81"`
	ExpLost82  float32 `elements:"name:exp_lost_82;type:float;size:4;text:未知;" gorm:"column:exp_lost_82;type:float;default:0;not null;" json:"exp_lost_82"`
	ExpLost83  float32 `elements:"name:exp_lost_83;type:float;size:4;text:未知;" gorm:"column:exp_lost_83;type:float;default:0;not null;" json:"exp_lost_83"`
	ExpLost84  float32 `elements:"name:exp_lost_84;type:float;size:4;text:未知;" gorm:"column:exp_lost_84;type:float;default:0;not null;" json:"exp_lost_84"`
	ExpLost85  float32 `elements:"name:exp_lost_85;type:float;size:4;text:未知;" gorm:"column:exp_lost_85;type:float;default:0;not null;" json:"exp_lost_85"`
	ExpLost86  float32 `elements:"name:exp_lost_86;type:float;size:4;text:未知;" gorm:"column:exp_lost_86;type:float;default:0;not null;" json:"exp_lost_86"`
	ExpLost87  float32 `elements:"name:exp_lost_87;type:float;size:4;text:未知;" gorm:"column:exp_lost_87;type:float;default:0;not null;" json:"exp_lost_87"`
	ExpLost88  float32 `elements:"name:exp_lost_88;type:float;size:4;text:未知;" gorm:"column:exp_lost_88;type:float;default:0;not null;" json:"exp_lost_88"`
	ExpLost89  float32 `elements:"name:exp_lost_89;type:float;size:4;text:未知;" gorm:"column:exp_lost_89;type:float;default:0;not null;" json:"exp_lost_89"`
	ExpLost90  float32 `elements:"name:exp_lost_90;type:float;size:4;text:未知;" gorm:"column:exp_lost_90;type:float;default:0;not null;" json:"exp_lost_90"`
	ExpLost91  float32 `elements:"name:exp_lost_91;type:float;size:4;text:未知;" gorm:"column:exp_lost_91;type:float;default:0;not null;" json:"exp_lost_91"`
	ExpLost92  float32 `elements:"name:exp_lost_92;type:float;size:4;text:未知;" gorm:"column:exp_lost_92;type:float;default:0;not null;" json:"exp_lost_92"`
	ExpLost93  float32 `elements:"name:exp_lost_93;type:float;size:4;text:未知;" gorm:"column:exp_lost_93;type:float;default:0;not null;" json:"exp_lost_93"`
	ExpLost94  float32 `elements:"name:exp_lost_94;type:float;size:4;text:未知;" gorm:"column:exp_lost_94;type:float;default:0;not null;" json:"exp_lost_94"`
	ExpLost95  float32 `elements:"name:exp_lost_95;type:float;size:4;text:未知;" gorm:"column:exp_lost_95;type:float;default:0;not null;" json:"exp_lost_95"`
	ExpLost96  float32 `elements:"name:exp_lost_96;type:float;size:4;text:未知;" gorm:"column:exp_lost_96;type:float;default:0;not null;" json:"exp_lost_96"`
	ExpLost97  float32 `elements:"name:exp_lost_97;type:float;size:4;text:未知;" gorm:"column:exp_lost_97;type:float;default:0;not null;" json:"exp_lost_97"`
	ExpLost98  float32 `elements:"name:exp_lost_98;type:float;size:4;text:未知;" gorm:"column:exp_lost_98;type:float;default:0;not null;" json:"exp_lost_98"`
	ExpLost99  float32 `elements:"name:exp_lost_99;type:float;size:4;text:未知;" gorm:"column:exp_lost_99;type:float;default:0;not null;" json:"exp_lost_99"`
	ExpLost100 float32 `elements:"name:exp_lost_100;type:float;size:4;text:未知;" gorm:"column:exp_lost_100;type:float;default:0;not null;" json:"exp_lost_100"`
	ExpLost101 float32 `elements:"name:exp_lost_101;type:float;size:4;text:未知;" gorm:"column:exp_lost_101;type:float;default:0;not null;" json:"exp_lost_101"`
	ExpLost102 float32 `elements:"name:exp_lost_102;type:float;size:4;text:未知;" gorm:"column:exp_lost_102;type:float;default:0;not null;" json:"exp_lost_102"`
	ExpLost103 float32 `elements:"name:exp_lost_103;type:float;size:4;text:未知;" gorm:"column:exp_lost_103;type:float;default:0;not null;" json:"exp_lost_103"`
	ExpLost104 float32 `elements:"name:exp_lost_104;type:float;size:4;text:未知;" gorm:"column:exp_lost_104;type:float;default:0;not null;" json:"exp_lost_104"`
	ExpLost105 float32 `elements:"name:exp_lost_105;type:float;size:4;text:未知;" gorm:"column:exp_lost_105;type:float;default:0;not null;" json:"exp_lost_105"`
	ExpLost106 float32 `elements:"name:exp_lost_106;type:float;size:4;text:未知;" gorm:"column:exp_lost_106;type:float;default:0;not null;" json:"exp_lost_106"`
	ExpLost107 float32 `elements:"name:exp_lost_107;type:float;size:4;text:未知;" gorm:"column:exp_lost_107;type:float;default:0;not null;" json:"exp_lost_107"`
	ExpLost108 float32 `elements:"name:exp_lost_108;type:float;size:4;text:未知;" gorm:"column:exp_lost_108;type:float;default:0;not null;" json:"exp_lost_108"`
	ExpLost109 float32 `elements:"name:exp_lost_109;type:float;size:4;text:未知;" gorm:"column:exp_lost_109;type:float;default:0;not null;" json:"exp_lost_109"`
	ExpLost110 float32 `elements:"name:exp_lost_110;type:float;size:4;text:未知;" gorm:"column:exp_lost_110;type:float;default:0;not null;" json:"exp_lost_110"`
	ExpLost111 float32 `elements:"name:exp_lost_111;type:float;size:4;text:未知;" gorm:"column:exp_lost_111;type:float;default:0;not null;" json:"exp_lost_111"`
	ExpLost112 float32 `elements:"name:exp_lost_112;type:float;size:4;text:未知;" gorm:"column:exp_lost_112;type:float;default:0;not null;" json:"exp_lost_112"`
	ExpLost113 float32 `elements:"name:exp_lost_113;type:float;size:4;text:未知;" gorm:"column:exp_lost_113;type:float;default:0;not null;" json:"exp_lost_113"`
	ExpLost114 float32 `elements:"name:exp_lost_114;type:float;size:4;text:未知;" gorm:"column:exp_lost_114;type:float;default:0;not null;" json:"exp_lost_114"`
	ExpLost115 float32 `elements:"name:exp_lost_115;type:float;size:4;text:未知;" gorm:"column:exp_lost_115;type:float;default:0;not null;" json:"exp_lost_115"`
	ExpLost116 float32 `elements:"name:exp_lost_116;type:float;size:4;text:未知;" gorm:"column:exp_lost_116;type:float;default:0;not null;" json:"exp_lost_116"`
	ExpLost117 float32 `elements:"name:exp_lost_117;type:float;size:4;text:未知;" gorm:"column:exp_lost_117;type:float;default:0;not null;" json:"exp_lost_117"`
	ExpLost118 float32 `elements:"name:exp_lost_118;type:float;size:4;text:未知;" gorm:"column:exp_lost_118;type:float;default:0;not null;" json:"exp_lost_118"`
	ExpLost119 float32 `elements:"name:exp_lost_119;type:float;size:4;text:未知;" gorm:"column:exp_lost_119;type:float;default:0;not null;" json:"exp_lost_119"`
	ExpLost120 float32 `elements:"name:exp_lost_120;type:float;size:4;text:未知;" gorm:"column:exp_lost_120;type:float;default:0;not null;" json:"exp_lost_120"`
	ExpLost121 float32 `elements:"name:exp_lost_121;type:float;size:4;text:未知;" gorm:"column:exp_lost_121;type:float;default:0;not null;" json:"exp_lost_121"`
	ExpLost122 float32 `elements:"name:exp_lost_122;type:float;size:4;text:未知;" gorm:"column:exp_lost_122;type:float;default:0;not null;" json:"exp_lost_122"`
	ExpLost123 float32 `elements:"name:exp_lost_123;type:float;size:4;text:未知;" gorm:"column:exp_lost_123;type:float;default:0;not null;" json:"exp_lost_123"`
	ExpLost124 float32 `elements:"name:exp_lost_124;type:float;size:4;text:未知;" gorm:"column:exp_lost_124;type:float;default:0;not null;" json:"exp_lost_124"`
	ExpLost125 float32 `elements:"name:exp_lost_125;type:float;size:4;text:未知;" gorm:"column:exp_lost_125;type:float;default:0;not null;" json:"exp_lost_125"`
	ExpLost126 float32 `elements:"name:exp_lost_126;type:float;size:4;text:未知;" gorm:"column:exp_lost_126;type:float;default:0;not null;" json:"exp_lost_126"`
	ExpLost127 float32 `elements:"name:exp_lost_127;type:float;size:4;text:未知;" gorm:"column:exp_lost_127;type:float;default:0;not null;" json:"exp_lost_127"`
	ExpLost128 float32 `elements:"name:exp_lost_128;type:float;size:4;text:未知;" gorm:"column:exp_lost_128;type:float;default:0;not null;" json:"exp_lost_128"`
	ExpLost129 float32 `elements:"name:exp_lost_129;type:float;size:4;text:未知;" gorm:"column:exp_lost_129;type:float;default:0;not null;" json:"exp_lost_129"`
	ExpLost130 float32 `elements:"name:exp_lost_130;type:float;size:4;text:未知;" gorm:"column:exp_lost_130;type:float;default:0;not null;" json:"exp_lost_130"`
	ExpLost131 float32 `elements:"name:exp_lost_131;type:float;size:4;text:未知;" gorm:"column:exp_lost_131;type:float;default:0;not null;" json:"exp_lost_131"`
	ExpLost132 float32 `elements:"name:exp_lost_132;type:float;size:4;text:未知;" gorm:"column:exp_lost_132;type:float;default:0;not null;" json:"exp_lost_132"`
	ExpLost133 float32 `elements:"name:exp_lost_133;type:float;size:4;text:未知;" gorm:"column:exp_lost_133;type:float;default:0;not null;" json:"exp_lost_133"`
	ExpLost134 float32 `elements:"name:exp_lost_134;type:float;size:4;text:未知;" gorm:"column:exp_lost_134;type:float;default:0;not null;" json:"exp_lost_134"`
	ExpLost135 float32 `elements:"name:exp_lost_135;type:float;size:4;text:未知;" gorm:"column:exp_lost_135;type:float;default:0;not null;" json:"exp_lost_135"`
	ExpLost136 float32 `elements:"name:exp_lost_136;type:float;size:4;text:未知;" gorm:"column:exp_lost_136;type:float;default:0;not null;" json:"exp_lost_136"`
	ExpLost137 float32 `elements:"name:exp_lost_137;type:float;size:4;text:未知;" gorm:"column:exp_lost_137;type:float;default:0;not null;" json:"exp_lost_137"`
	ExpLost138 float32 `elements:"name:exp_lost_138;type:float;size:4;text:未知;" gorm:"column:exp_lost_138;type:float;default:0;not null;" json:"exp_lost_138"`
	ExpLost139 float32 `elements:"name:exp_lost_139;type:float;size:4;text:未知;" gorm:"column:exp_lost_139;type:float;default:0;not null;" json:"exp_lost_139"`
	ExpLost140 float32 `elements:"name:exp_lost_140;type:float;size:4;text:未知;" gorm:"column:exp_lost_140;type:float;default:0;not null;" json:"exp_lost_140"`
	ExpLost141 float32 `elements:"name:exp_lost_141;type:float;size:4;text:未知;" gorm:"column:exp_lost_141;type:float;default:0;not null;" json:"exp_lost_141"`
	ExpLost142 float32 `elements:"name:exp_lost_142;type:float;size:4;text:未知;" gorm:"column:exp_lost_142;type:float;default:0;not null;" json:"exp_lost_142"`
	ExpLost143 float32 `elements:"name:exp_lost_143;type:float;size:4;text:未知;" gorm:"column:exp_lost_143;type:float;default:0;not null;" json:"exp_lost_143"`
	ExpLost144 float32 `elements:"name:exp_lost_144;type:float;size:4;text:未知;" gorm:"column:exp_lost_144;type:float;default:0;not null;" json:"exp_lost_144"`
	ExpLost145 float32 `elements:"name:exp_lost_145;type:float;size:4;text:未知;" gorm:"column:exp_lost_145;type:float;default:0;not null;" json:"exp_lost_145"`
	ExpLost146 float32 `elements:"name:exp_lost_146;type:float;size:4;text:未知;" gorm:"column:exp_lost_146;type:float;default:0;not null;" json:"exp_lost_146"`
	ExpLost147 float32 `elements:"name:exp_lost_147;type:float;size:4;text:未知;" gorm:"column:exp_lost_147;type:float;default:0;not null;" json:"exp_lost_147"`
	ExpLost148 float32 `elements:"name:exp_lost_148;type:float;size:4;text:未知;" gorm:"column:exp_lost_148;type:float;default:0;not null;" json:"exp_lost_148"`
	ExpLost149 float32 `elements:"name:exp_lost_149;type:float;size:4;text:未知;" gorm:"column:exp_lost_149;type:float;default:0;not null;" json:"exp_lost_149"`
	ExpLost150 float32 `elements:"name:exp_lost_150;type:float;size:4;text:未知;" gorm:"column:exp_lost_150;type:float;default:0;not null;" json:"exp_lost_150"`
	ExpLost151 float32 `elements:"name:exp_lost_151;type:float;size:4;text:未知;" gorm:"column:exp_lost_151;type:float;default:0;not null;" json:"exp_lost_151"`
	ExpLost152 float32 `elements:"name:exp_lost_152;type:float;size:4;text:未知;" gorm:"column:exp_lost_152;type:float;default:0;not null;" json:"exp_lost_152"`
	ExpLost153 float32 `elements:"name:exp_lost_153;type:float;size:4;text:未知;" gorm:"column:exp_lost_153;type:float;default:0;not null;" json:"exp_lost_153"`
	ExpLost154 float32 `elements:"name:exp_lost_154;type:float;size:4;text:未知;" gorm:"column:exp_lost_154;type:float;default:0;not null;" json:"exp_lost_154"`
	ExpLost155 float32 `elements:"name:exp_lost_155;type:float;size:4;text:未知;" gorm:"column:exp_lost_155;type:float;default:0;not null;" json:"exp_lost_155"`
	ExpLost156 float32 `elements:"name:exp_lost_156;type:float;size:4;text:未知;" gorm:"column:exp_lost_156;type:float;default:0;not null;" json:"exp_lost_156"`
	ExpLost157 float32 `elements:"name:exp_lost_157;type:float;size:4;text:未知;" gorm:"column:exp_lost_157;type:float;default:0;not null;" json:"exp_lost_157"`
	ExpLost158 float32 `elements:"name:exp_lost_158;type:float;size:4;text:未知;" gorm:"column:exp_lost_158;type:float;default:0;not null;" json:"exp_lost_158"`
	ExpLost159 float32 `elements:"name:exp_lost_159;type:float;size:4;text:未知;" gorm:"column:exp_lost_159;type:float;default:0;not null;" json:"exp_lost_159"`
	ExpLost160 float32 `elements:"name:exp_lost_160;type:float;size:4;text:未知;" gorm:"column:exp_lost_160;type:float;default:0;not null;" json:"exp_lost_160"`
	ExpLost161 float32 `elements:"name:exp_lost_161;type:float;size:4;text:未知;" gorm:"column:exp_lost_161;type:float;default:0;not null;" json:"exp_lost_161"`
	ExpLost162 float32 `elements:"name:exp_lost_162;type:float;size:4;text:未知;" gorm:"column:exp_lost_162;type:float;default:0;not null;" json:"exp_lost_162"`
	ExpLost163 float32 `elements:"name:exp_lost_163;type:float;size:4;text:未知;" gorm:"column:exp_lost_163;type:float;default:0;not null;" json:"exp_lost_163"`
	ExpLost164 float32 `elements:"name:exp_lost_164;type:float;size:4;text:未知;" gorm:"column:exp_lost_164;type:float;default:0;not null;" json:"exp_lost_164"`
	ExpLost165 float32 `elements:"name:exp_lost_165;type:float;size:4;text:未知;" gorm:"column:exp_lost_165;type:float;default:0;not null;" json:"exp_lost_165"`
	ExpLost166 float32 `elements:"name:exp_lost_166;type:float;size:4;text:未知;" gorm:"column:exp_lost_166;type:float;default:0;not null;" json:"exp_lost_166"`
	ExpLost167 float32 `elements:"name:exp_lost_167;type:float;size:4;text:未知;" gorm:"column:exp_lost_167;type:float;default:0;not null;" json:"exp_lost_167"`
	ExpLost168 float32 `elements:"name:exp_lost_168;type:float;size:4;text:未知;" gorm:"column:exp_lost_168;type:float;default:0;not null;" json:"exp_lost_168"`
	ExpLost169 float32 `elements:"name:exp_lost_169;type:float;size:4;text:未知;" gorm:"column:exp_lost_169;type:float;default:0;not null;" json:"exp_lost_169"`
	ExpLost170 float32 `elements:"name:exp_lost_170;type:float;size:4;text:未知;" gorm:"column:exp_lost_170;type:float;default:0;not null;" json:"exp_lost_170"`
	ExpLost171 float32 `elements:"name:exp_lost_171;type:float;size:4;text:未知;" gorm:"column:exp_lost_171;type:float;default:0;not null;" json:"exp_lost_171"`
	ExpLost172 float32 `elements:"name:exp_lost_172;type:float;size:4;text:未知;" gorm:"column:exp_lost_172;type:float;default:0;not null;" json:"exp_lost_172"`
	ExpLost173 float32 `elements:"name:exp_lost_173;type:float;size:4;text:未知;" gorm:"column:exp_lost_173;type:float;default:0;not null;" json:"exp_lost_173"`
	ExpLost174 float32 `elements:"name:exp_lost_174;type:float;size:4;text:未知;" gorm:"column:exp_lost_174;type:float;default:0;not null;" json:"exp_lost_174"`
	ExpLost175 float32 `elements:"name:exp_lost_175;type:float;size:4;text:未知;" gorm:"column:exp_lost_175;type:float;default:0;not null;" json:"exp_lost_175"`
	ExpLost176 float32 `elements:"name:exp_lost_176;type:float;size:4;text:未知;" gorm:"column:exp_lost_176;type:float;default:0;not null;" json:"exp_lost_176"`
	ExpLost177 float32 `elements:"name:exp_lost_177;type:float;size:4;text:未知;" gorm:"column:exp_lost_177;type:float;default:0;not null;" json:"exp_lost_177"`
	ExpLost178 float32 `elements:"name:exp_lost_178;type:float;size:4;text:未知;" gorm:"column:exp_lost_178;type:float;default:0;not null;" json:"exp_lost_178"`
	ExpLost179 float32 `elements:"name:exp_lost_179;type:float;size:4;text:未知;" gorm:"column:exp_lost_179;type:float;default:0;not null;" json:"exp_lost_179"`
	ExpLost180 float32 `elements:"name:exp_lost_180;type:float;size:4;text:未知;" gorm:"column:exp_lost_180;type:float;default:0;not null;" json:"exp_lost_180"`
	ExpLost181 float32 `elements:"name:exp_lost_181;type:float;size:4;text:未知;" gorm:"column:exp_lost_181;type:float;default:0;not null;" json:"exp_lost_181"`
	ExpLost182 float32 `elements:"name:exp_lost_182;type:float;size:4;text:未知;" gorm:"column:exp_lost_182;type:float;default:0;not null;" json:"exp_lost_182"`
	ExpLost183 float32 `elements:"name:exp_lost_183;type:float;size:4;text:未知;" gorm:"column:exp_lost_183;type:float;default:0;not null;" json:"exp_lost_183"`
	ExpLost184 float32 `elements:"name:exp_lost_184;type:float;size:4;text:未知;" gorm:"column:exp_lost_184;type:float;default:0;not null;" json:"exp_lost_184"`
	ExpLost185 float32 `elements:"name:exp_lost_185;type:float;size:4;text:未知;" gorm:"column:exp_lost_185;type:float;default:0;not null;" json:"exp_lost_185"`
	ExpLost186 float32 `elements:"name:exp_lost_186;type:float;size:4;text:未知;" gorm:"column:exp_lost_186;type:float;default:0;not null;" json:"exp_lost_186"`
	ExpLost187 float32 `elements:"name:exp_lost_187;type:float;size:4;text:未知;" gorm:"column:exp_lost_187;type:float;default:0;not null;" json:"exp_lost_187"`
	ExpLost188 float32 `elements:"name:exp_lost_188;type:float;size:4;text:未知;" gorm:"column:exp_lost_188;type:float;default:0;not null;" json:"exp_lost_188"`
	ExpLost189 float32 `elements:"name:exp_lost_189;type:float;size:4;text:未知;" gorm:"column:exp_lost_189;type:float;default:0;not null;" json:"exp_lost_189"`
	ExpLost190 float32 `elements:"name:exp_lost_190;type:float;size:4;text:未知;" gorm:"column:exp_lost_190;type:float;default:0;not null;" json:"exp_lost_190"`
	ExpLost191 float32 `elements:"name:exp_lost_191;type:float;size:4;text:未知;" gorm:"column:exp_lost_191;type:float;default:0;not null;" json:"exp_lost_191"`
	ExpLost192 float32 `elements:"name:exp_lost_192;type:float;size:4;text:未知;" gorm:"column:exp_lost_192;type:float;default:0;not null;" json:"exp_lost_192"`
	ExpLost193 float32 `elements:"name:exp_lost_193;type:float;size:4;text:未知;" gorm:"column:exp_lost_193;type:float;default:0;not null;" json:"exp_lost_193"`
	ExpLost194 float32 `elements:"name:exp_lost_194;type:float;size:4;text:未知;" gorm:"column:exp_lost_194;type:float;default:0;not null;" json:"exp_lost_194"`
	ExpLost195 float32 `elements:"name:exp_lost_195;type:float;size:4;text:未知;" gorm:"column:exp_lost_195;type:float;default:0;not null;" json:"exp_lost_195"`
	ExpLost196 float32 `elements:"name:exp_lost_196;type:float;size:4;text:未知;" gorm:"column:exp_lost_196;type:float;default:0;not null;" json:"exp_lost_196"`
	ExpLost197 float32 `elements:"name:exp_lost_197;type:float;size:4;text:未知;" gorm:"column:exp_lost_197;type:float;default:0;not null;" json:"exp_lost_197"`
	ExpLost198 float32 `elements:"name:exp_lost_198;type:float;size:4;text:未知;" gorm:"column:exp_lost_198;type:float;default:0;not null;" json:"exp_lost_198"`
	ExpLost199 float32 `elements:"name:exp_lost_199;type:float;size:4;text:未知;" gorm:"column:exp_lost_199;type:float;default:0;not null;" json:"exp_lost_199"`
	ExpLost200 float32 `elements:"name:exp_lost_200;type:float;size:4;text:未知;" gorm:"column:exp_lost_200;type:float;default:0;not null;" json:"exp_lost_200"`
	ExpLost201 float32 `elements:"name:exp_lost_201;type:float;size:4;text:未知;" gorm:"column:exp_lost_201;type:float;default:0;not null;" json:"exp_lost_201"`
	ExpLost202 float32 `elements:"name:exp_lost_202;type:float;size:4;text:未知;" gorm:"column:exp_lost_202;type:float;default:0;not null;" json:"exp_lost_202"`
	ExpLost203 float32 `elements:"name:exp_lost_203;type:float;size:4;text:未知;" gorm:"column:exp_lost_203;type:float;default:0;not null;" json:"exp_lost_203"`
	ExpLost204 float32 `elements:"name:exp_lost_204;type:float;size:4;text:未知;" gorm:"column:exp_lost_204;type:float;default:0;not null;" json:"exp_lost_204"`
	ExpLost205 float32 `elements:"name:exp_lost_205;type:float;size:4;text:未知;" gorm:"column:exp_lost_205;type:float;default:0;not null;" json:"exp_lost_205"`
	ExpLost206 float32 `elements:"name:exp_lost_206;type:float;size:4;text:未知;" gorm:"column:exp_lost_206;type:float;default:0;not null;" json:"exp_lost_206"`
	ExpLost207 float32 `elements:"name:exp_lost_207;type:float;size:4;text:未知;" gorm:"column:exp_lost_207;type:float;default:0;not null;" json:"exp_lost_207"`
	ExpLost208 float32 `elements:"name:exp_lost_208;type:float;size:4;text:未知;" gorm:"column:exp_lost_208;type:float;default:0;not null;" json:"exp_lost_208"`
	ExpLost209 float32 `elements:"name:exp_lost_209;type:float;size:4;text:未知;" gorm:"column:exp_lost_209;type:float;default:0;not null;" json:"exp_lost_209"`
	ExpLost210 float32 `elements:"name:exp_lost_210;type:float;size:4;text:未知;" gorm:"column:exp_lost_210;type:float;default:0;not null;" json:"exp_lost_210"`
	ExpLost211 float32 `elements:"name:exp_lost_211;type:float;size:4;text:未知;" gorm:"column:exp_lost_211;type:float;default:0;not null;" json:"exp_lost_211"`
	ExpLost212 float32 `elements:"name:exp_lost_212;type:float;size:4;text:未知;" gorm:"column:exp_lost_212;type:float;default:0;not null;" json:"exp_lost_212"`
	ExpLost213 float32 `elements:"name:exp_lost_213;type:float;size:4;text:未知;" gorm:"column:exp_lost_213;type:float;default:0;not null;" json:"exp_lost_213"`
	ExpLost214 float32 `elements:"name:exp_lost_214;type:float;size:4;text:未知;" gorm:"column:exp_lost_214;type:float;default:0;not null;" json:"exp_lost_214"`
	ExpLost215 float32 `elements:"name:exp_lost_215;type:float;size:4;text:未知;" gorm:"column:exp_lost_215;type:float;default:0;not null;" json:"exp_lost_215"`
	ExpLost216 float32 `elements:"name:exp_lost_216;type:float;size:4;text:未知;" gorm:"column:exp_lost_216;type:float;default:0;not null;" json:"exp_lost_216"`
	ExpLost217 float32 `elements:"name:exp_lost_217;type:float;size:4;text:未知;" gorm:"column:exp_lost_217;type:float;default:0;not null;" json:"exp_lost_217"`
	ExpLost218 float32 `elements:"name:exp_lost_218;type:float;size:4;text:未知;" gorm:"column:exp_lost_218;type:float;default:0;not null;" json:"exp_lost_218"`
	ExpLost219 float32 `elements:"name:exp_lost_219;type:float;size:4;text:未知;" gorm:"column:exp_lost_219;type:float;default:0;not null;" json:"exp_lost_219"`
	ExpLost220 float32 `elements:"name:exp_lost_220;type:float;size:4;text:未知;" gorm:"column:exp_lost_220;type:float;default:0;not null;" json:"exp_lost_220"`
	ExpLost221 float32 `elements:"name:exp_lost_221;type:float;size:4;text:未知;" gorm:"column:exp_lost_221;type:float;default:0;not null;" json:"exp_lost_221"`
	ExpLost222 float32 `elements:"name:exp_lost_222;type:float;size:4;text:未知;" gorm:"column:exp_lost_222;type:float;default:0;not null;" json:"exp_lost_222"`
	ExpLost223 float32 `elements:"name:exp_lost_223;type:float;size:4;text:未知;" gorm:"column:exp_lost_223;type:float;default:0;not null;" json:"exp_lost_223"`
	ExpLost224 float32 `elements:"name:exp_lost_224;type:float;size:4;text:未知;" gorm:"column:exp_lost_224;type:float;default:0;not null;" json:"exp_lost_224"`
	ExpLost225 float32 `elements:"name:exp_lost_225;type:float;size:4;text:未知;" gorm:"column:exp_lost_225;type:float;default:0;not null;" json:"exp_lost_225"`
	ExpLost226 float32 `elements:"name:exp_lost_226;type:float;size:4;text:未知;" gorm:"column:exp_lost_226;type:float;default:0;not null;" json:"exp_lost_226"`
	ExpLost227 float32 `elements:"name:exp_lost_227;type:float;size:4;text:未知;" gorm:"column:exp_lost_227;type:float;default:0;not null;" json:"exp_lost_227"`
	ExpLost228 float32 `elements:"name:exp_lost_228;type:float;size:4;text:未知;" gorm:"column:exp_lost_228;type:float;default:0;not null;" json:"exp_lost_228"`
	ExpLost229 float32 `elements:"name:exp_lost_229;type:float;size:4;text:未知;" gorm:"column:exp_lost_229;type:float;default:0;not null;" json:"exp_lost_229"`
	ExpLost230 float32 `elements:"name:exp_lost_230;type:float;size:4;text:未知;" gorm:"column:exp_lost_230;type:float;default:0;not null;" json:"exp_lost_230"`
	ExpLost231 float32 `elements:"name:exp_lost_231;type:float;size:4;text:未知;" gorm:"column:exp_lost_231;type:float;default:0;not null;" json:"exp_lost_231"`
	ExpLost232 float32 `elements:"name:exp_lost_232;type:float;size:4;text:未知;" gorm:"column:exp_lost_232;type:float;default:0;not null;" json:"exp_lost_232"`
	ExpLost233 float32 `elements:"name:exp_lost_233;type:float;size:4;text:未知;" gorm:"column:exp_lost_233;type:float;default:0;not null;" json:"exp_lost_233"`
	ExpLost234 float32 `elements:"name:exp_lost_234;type:float;size:4;text:未知;" gorm:"column:exp_lost_234;type:float;default:0;not null;" json:"exp_lost_234"`
	ExpLost235 float32 `elements:"name:exp_lost_235;type:float;size:4;text:未知;" gorm:"column:exp_lost_235;type:float;default:0;not null;" json:"exp_lost_235"`
	ExpLost236 float32 `elements:"name:exp_lost_236;type:float;size:4;text:未知;" gorm:"column:exp_lost_236;type:float;default:0;not null;" json:"exp_lost_236"`
	ExpLost237 float32 `elements:"name:exp_lost_237;type:float;size:4;text:未知;" gorm:"column:exp_lost_237;type:float;default:0;not null;" json:"exp_lost_237"`
	ExpLost238 float32 `elements:"name:exp_lost_238;type:float;size:4;text:未知;" gorm:"column:exp_lost_238;type:float;default:0;not null;" json:"exp_lost_238"`
	ExpLost239 float32 `elements:"name:exp_lost_239;type:float;size:4;text:未知;" gorm:"column:exp_lost_239;type:float;default:0;not null;" json:"exp_lost_239"`
	ExpLost240 float32 `elements:"name:exp_lost_240;type:float;size:4;text:未知;" gorm:"column:exp_lost_240;type:float;default:0;not null;" json:"exp_lost_240"`
	ExpLost241 float32 `elements:"name:exp_lost_241;type:float;size:4;text:未知;" gorm:"column:exp_lost_241;type:float;default:0;not null;" json:"exp_lost_241"`
	ExpLost242 float32 `elements:"name:exp_lost_242;type:float;size:4;text:未知;" gorm:"column:exp_lost_242;type:float;default:0;not null;" json:"exp_lost_242"`
	ExpLost243 float32 `elements:"name:exp_lost_243;type:float;size:4;text:未知;" gorm:"column:exp_lost_243;type:float;default:0;not null;" json:"exp_lost_243"`
	ExpLost244 float32 `elements:"name:exp_lost_244;type:float;size:4;text:未知;" gorm:"column:exp_lost_244;type:float;default:0;not null;" json:"exp_lost_244"`
	ExpLost245 float32 `elements:"name:exp_lost_245;type:float;size:4;text:未知;" gorm:"column:exp_lost_245;type:float;default:0;not null;" json:"exp_lost_245"`
	ExpLost246 float32 `elements:"name:exp_lost_246;type:float;size:4;text:未知;" gorm:"column:exp_lost_246;type:float;default:0;not null;" json:"exp_lost_246"`
	ExpLost247 float32 `elements:"name:exp_lost_247;type:float;size:4;text:未知;" gorm:"column:exp_lost_247;type:float;default:0;not null;" json:"exp_lost_247"`
	ExpLost248 float32 `elements:"name:exp_lost_248;type:float;size:4;text:未知;" gorm:"column:exp_lost_248;type:float;default:0;not null;" json:"exp_lost_248"`
	ExpLost249 float32 `elements:"name:exp_lost_249;type:float;size:4;text:未知;" gorm:"column:exp_lost_249;type:float;default:0;not null;" json:"exp_lost_249"`
	ExpLost250 float32 `elements:"name:exp_lost_250;type:float;size:4;text:未知;" gorm:"column:exp_lost_250;type:float;default:0;not null;" json:"exp_lost_250"`
	ExpLost251 float32 `elements:"name:exp_lost_251;type:float;size:4;text:未知;" gorm:"column:exp_lost_251;type:float;default:0;not null;" json:"exp_lost_251"`
	ExpLost252 float32 `elements:"name:exp_lost_252;type:float;size:4;text:未知;" gorm:"column:exp_lost_252;type:float;default:0;not null;" json:"exp_lost_252"`
	ExpLost253 float32 `elements:"name:exp_lost_253;type:float;size:4;text:未知;" gorm:"column:exp_lost_253;type:float;default:0;not null;" json:"exp_lost_253"`
	ExpLost254 float32 `elements:"name:exp_lost_254;type:float;size:4;text:未知;" gorm:"column:exp_lost_254;type:float;default:0;not null;" json:"exp_lost_254"`
	ExpLost255 float32 `elements:"name:exp_lost_255;type:float;size:4;text:未知;" gorm:"column:exp_lost_255;type:float;default:0;not null;" json:"exp_lost_255"`
	ExpLost256 float32 `elements:"name:exp_lost_256;type:float;size:4;text:未知;" gorm:"column:exp_lost_256;type:float;default:0;not null;" json:"exp_lost_256"`
}

func (PlayerSecondlevelConfig) TableName() string {
	return "el_playersecondlevelconfig"
}

func (e *PlayerSecondlevelConfig) GetSize() (size int, err error) {
	return structEx.GetSize(e)
}

func (e *PlayerSecondlevelConfig) SetData(data []byte) (err error) {
	return structEx.SetData(e, data)
}
